Data Loading

In [1]:
import pandas as pd
import numpy as np
import os
from pathlib import Path

SAVE_DIR = "/kaggle/working"
os.makedirs(SAVE_DIR, exist_ok=True)

DATASET_DIR = "/kaggle/input/competitions/icdar-2026-circleid-writer-identification"
PRETRAINED_DIR = "/kaggle/input/datasets/cbdsigmas/tranfer-to-writer-model"

train_1 = pd.read_csv(f"{DATASET_DIR}/train.csv")
additional_path = Path(DATASET_DIR) / "additional_train.csv"
if additional_path.exists():
    train_2 = pd.read_csv(additional_path)
    train_df = pd.concat([train_1, train_2], ignore_index=True)
    del(train_2)
else:
    train_df = train_1.copy()

test_df = pd.read_csv(f"{DATASET_DIR}/test.csv")
sample_submission = pd.read_csv(f"{DATASET_DIR}/sample_submission.csv")

del(train_1)
print(f"train_df shape: {train_df.shape}")
print(f"test_df shape: {test_df.shape}")

train_df.sample(min(7, len(train_df)))

train_df shape: (40250, 4)
test_df shape: (5905, 2)

       image_id        image_path writer_id  pen_id
11586     19564  images/19564.png       W38       4
13020     21996  images/21996.png       W40       3
5167       8715  images/08715.png       W03       3
31524     18827  images/18827.png       W41       4
11595     19577  images/19577.png       W06       3
13694     23082  images/23082.png       W50       6
32800     21947  images/21947.png        -1       3

In [2]:
if "image_path" in train_df.columns:
    train_df["image_path"] = train_df["image_path"].astype(str).map(
        lambda x: x if x.startswith("/") else f"{DATASET_DIR}/{x}"
    )
else:
    train_df["image_path"] = train_df["image_id"].astype(str).map(
        lambda x: f"{DATASET_DIR}/images/{x}.png"
    )

if "image_path" in test_df.columns:
    test_df["image_path"] = test_df["image_path"].astype(str).map(
        lambda x: x if x.startswith("/") else f"{DATASET_DIR}/{x}"
    )
else:
    test_df["image_path"] = test_df["image_id"].astype(str).map(
        lambda x: f"{DATASET_DIR}/images/{x}.png"
    )

train_df["writer_id"] = train_df["writer_id"].astype(str)
unlabeled_mask = train_df["writer_id"].eq("-1")
unlabeled_count = int(unlabeled_mask.sum())

train_df = train_df.loc[~unlabeled_mask].reset_index(drop=True)

writer_ids = sorted(train_df["writer_id"].unique())
writer_to_label = {writer_id: idx for idx, writer_id in enumerate(writer_ids)}
label_to_writer = {idx: writer_id for writer_id, idx in writer_to_label.items()}
NUM_CLASSES = len(writer_ids)

train_df["label"] = train_df["writer_id"].map(writer_to_label)
print("Dropped unlabeled rows:", unlabeled_count)
print("NUM_CLASSES:", NUM_CLASSES)
train_df[["writer_id", "label"]].head()

Dropped unlabeled rows: 5600
NUM_CLASSES: 44

  writer_id  label
0       W27     21
1       W17     15
2       W01      0
3       W17     15
4       W24     19

In [3]:
import os
import torch

XLA_AVAILABLE = False
pl = None
xm = None

try:
    import torch_xla
    import torch_xla.core.xla_model as xm
    import torch_xla.distributed.parallel_loader as pl
    XLA_AVAILABLE = True
except ImportError:
    pass

USE_TPU = XLA_AVAILABLE and (
    os.environ.get("TPU_NAME") is not None
    or os.environ.get("PJRT_DEVICE") == "TPU"
)

if USE_TPU:
    os.environ.setdefault("PJRT_DEVICE", "TPU")
    device = xm.xla_device()
    print("Using TPU:", device)
elif torch.cuda.is_available():
    device = torch.device("cuda")
    print("Using GPU:", device)
else:
    device = torch.device("cpu")
    print("Using CPU:", device)

/usr/local/lib/python3.12/site-packages/torch_xla/__init__.py:258: UserWarning: `tensorflow` can conflict with `torch-xla`. Prefer `tensorflow-cpu` when using PyTorch/XLA. To silence this warning, `pip uninstall -y tensorflow && pip install tensorflow-cpu`. If you are in a notebook environment such as Colab or Kaggle, restart your notebook runtime afterwards.
  warnings.warn(

/tmp/ipykernel_74/3154709306.py:23: DeprecationWarning: Use torch_xla.device instead
  device = xm.xla_device()
WARNING: Logging before InitGoogle() is written to STDERR
E0000 00:00:1774074844.718114      74 common_lib.cc:648] Could not set metric server port: INVALID_ARGUMENT: Could not find SliceBuilder port 8471 in any of the 0 ports provided in `tpu_process_addresses`="local"
=== Source Location Trace: ===
learning/45eac/tfrc/runtime/common_lib.cc:238

Using TPU: xla:0

Train/validation split

In [4]:
from sklearn.model_selection import train_test_split

train_split_df, val_split_df = train_test_split(
    train_df,
    test_size=0.15,
    random_state=42,
    stratify=train_df["label"]
)

train_split_df = train_split_df.reset_index(drop=True)
val_split_df = val_split_df.reset_index(drop=True)

print(train_split_df.shape, val_split_df.shape)

(29452, 5) (5198, 5)

Dataset creation

In [5]:
from torch.utils.data import Dataset
from PIL import Image
import torchvision.transforms as transforms

class CircleDataset(Dataset):
    def __init__(
        self,
        df,
        img_root,
        transform=None,
        label_map=None,
        is_test=False,
        return_path=False
    ):
        self.df = df.reset_index(drop=True)
        self.root = Path(img_root)
        self.transform = transform
        self.label_map = label_map
        self.is_test = is_test
        self.return_path = return_path

        # Auto-create label map if not provided (train mode only)
        if not self.is_test and self.label_map is None:
            unique_labels = sorted(self.df["writer_id"].unique())
            self.label_map = {k: i for i, k in enumerate(unique_labels)}

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        # Robust path handling
        img_path = self.root / row["image_path"]

        # Safe image loading (prevents crash on corrupted files)
        try:
            image = Image.open(img_path).convert("RGB")
        except Exception:
            # fallback: blank image
            image = Image.new("RGB", (224, 224), (0, 0, 0))

        if self.transform:
            image = self.transform(image)

        if self.is_test:
            if self.return_path:
                return image, row["image_id"], str(img_path)
            return image, row["image_id"]

        # Label encoding
        label = self.label_map[row["writer_id"]]

        if self.return_path:
            return image, label, str(img_path)

        return image, label

Image Transformation

In [6]:
from torchvision import transforms

normalize = transforms.Normalize(
    mean=[0.485, 0.456, 0.406],
    std=[0.229, 0.224, 0.225]
)

train_tfms = transforms.Compose([
    transforms.Resize((224, 224)),

    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.2),

    transforms.RandomRotation(degrees=20),

    transforms.RandomAffine(
        degrees=0,
        translate=(0.1, 0.1),
        scale=(0.9, 1.1)
    ),

    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2,
        saturation=0.1,
        hue=0.05
    ),

    transforms.ToTensor(),

    normalize,

    transforms.RandomErasing(
        p=0.2,
        scale=(0.02, 0.1),
        ratio=(0.3, 3.3)
    ),
])


val_tfms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    normalize
])

Loading Model

In [7]:
import torch.nn as nn
from torchvision.models import resnet18, convnext_tiny

PRETRAINED_PATHS = {
    "resnet": f"{PRETRAINED_DIR}/resnet_best.pth",
    "convnext": f"{PRETRAINED_DIR}/convnext_best.pth",
}


def load_pretrained_backbone(model, model_name):
    ckpt_path = PRETRAINED_PATHS[model_name]

    if not os.path.exists(ckpt_path):
        print(f"Missing pretrained {model_name} checkpoint: {ckpt_path}")
        return model

    checkpoint = torch.load(ckpt_path, map_location="cpu")
    if isinstance(checkpoint, dict):
        if "state_dict" in checkpoint:
            checkpoint = checkpoint["state_dict"]
        elif "model_state_dict" in checkpoint:
            checkpoint = checkpoint["model_state_dict"]
        elif "model" in checkpoint and isinstance(checkpoint["model"], dict):
            checkpoint = checkpoint["model"]

    checkpoint = {
        key.replace("module.", ""): value
        for key, value in checkpoint.items()
    }

    if model_name == "resnet":
        checkpoint = {
            key: value for key, value in checkpoint.items()
            if not key.startswith("fc.")
        }
    else:
        checkpoint = {
            key: value for key, value in checkpoint.items()
            if not key.startswith("classifier.2")
        }

    missing, unexpected = model.load_state_dict(checkpoint, strict=False)
    print(f"Loaded pretrained {model_name} from {ckpt_path}")
    print("Missing keys:", missing)
    print("Unexpected keys:", unexpected)
    return model


def build_model(model_name="resnet"):

    if model_name == "resnet":

        model = resnet18(weights="IMAGENET1K_V1")
        model.fc = nn.Sequential(
            nn.Dropout(0.2),
            nn.Linear(model.fc.in_features, NUM_CLASSES)
        )

    elif model_name == "convnext":

        model = convnext_tiny(weights="IMAGENET1K_V1")
        model.classifier[2] = nn.Sequential(
            nn.Dropout(0.2),
            nn.Linear(model.classifier[2].in_features, NUM_CLASSES)
        )

    model = load_pretrained_backbone(model, model_name)
    return model

Model Training

In [8]:
import torch
import torch.nn.functional as F
from tqdm import tqdm

IS_XLA = str(device).startswith("xla")

def train_epoch(model, loader, optimizer, device):
    model.train()
    total_loss = 0

    for images, labels in tqdm(loader):
        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        logits = model(images)
        loss = F.cross_entropy(logits, labels, label_smoothing=0.05)

        loss.backward()

        if IS_XLA:
            xm.optimizer_step(optimizer, barrier=True)
            xm.mark_step()
        else:
            optimizer.step()

        total_loss += loss.item()

    return total_loss / len(loader)

In [9]:
@torch.no_grad()
def validate(model, loader, device):
    model.eval()

    correct = 0
    total = 0

    for images, labels in loader:
        images = images.to(device)
        labels = labels.to(device)

        logits = model(images)

        preds = logits.argmax(1)

        correct += (preds == labels).sum().item()
        total += labels.size(0)

        if IS_XLA:
            xm.mark_step()

    return correct / total

In [10]:
from torch.utils.data import DataLoader

BATCH_SIZE = 96
EPOCHS_resnet = 6
EPOCHS_convnext = 4
NUM_WORKERS = 2
PIN_MEMORY = not IS_XLA
LOWER_LR = 1e-4

models = []

train_ds = CircleDataset(train_split_df, DATASET_DIR, train_tfms)
val_ds = CircleDataset(val_split_df, DATASET_DIR, val_tfms)

train_loader = DataLoader(
    train_ds,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=NUM_WORKERS,
    pin_memory=PIN_MEMORY,
    drop_last=True
)

val_loader = DataLoader(
    val_ds,
    batch_size=BATCH_SIZE,
    num_workers=NUM_WORKERS,
    pin_memory=PIN_MEMORY
)

for model_name in ["resnet", "convnext"]:

    print(f"Training {model_name}")

    model = build_model(model_name).to(device)
    best_path = os.path.join(SAVE_DIR, f"writer_{model_name}_best.pth")

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=LOWER_LR,
        weight_decay=1e-4
    )

    if model_name == "resnet":
        EPOCHS = EPOCHS_resnet
    else:
        EPOCHS = EPOCHS_convnext

    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer,
        T_max=EPOCHS
    )

    best_val_acc = 0.0

    for epoch in range(EPOCHS):

        if IS_XLA:
            epoch_train_loader = pl.MpDeviceLoader(train_loader, device)
            epoch_val_loader = pl.MpDeviceLoader(val_loader, device)
        else:
            epoch_train_loader = train_loader
            epoch_val_loader = val_loader

        train_loss = train_epoch(model, epoch_train_loader, optimizer, device)

        val_acc = validate(model, epoch_val_loader, device)

        print(f"{model_name} Epoch {epoch} loss {train_loss:.4f} val_acc {val_acc:.4f}")

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            torch.save(model.state_dict(), best_path)
            print(f"Saved best {model_name} to {best_path}")

        scheduler.step()

    print(f"Best {model_name} val_acc: {best_val_acc:.4f}")
    state_dict = torch.load(best_path, map_location="cpu")
    model.load_state_dict(state_dict, strict=False)  # optional if mismatch
    model.to(device)
    model.eval()
    models.append(model)

Training resnet
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth

  0%|          | 0.00/44.7M [00:00<?, ?B/s]

 25%|██▍       | 11.0M/44.7M [00:00<00:00, 115MB/s]

 87%|████████▋ | 39.0M/44.7M [00:00<00:00, 220MB/s]

100%|██████████| 44.7M/44.7M [00:00<00:00, 212MB/s]

Loaded pretrained resnet from /kaggle/input/datasets/cbdsigmas/tranfer-to-writer-model/resnet_best.pth
Missing keys: ['fc.1.weight', 'fc.1.bias']
Unexpected keys: []

  0%|          | 0/306 [00:00<?, ?it/s]

/usr/local/lib/python3.12/site-packages/jax/_src/cloud_tpu_init.py:93: UserWarning: Transparent hugepages are not enabled. TPU runtime startup and shutdown time should be significantly improved on TPU v5e and newer. If not already set, you may need to enable transparent hugepages in your VM image (sudo sh -c "echo always > /sys/kernel/mm/transparent_hugepage/enabled")
  warnings.warn(

/tmp/ipykernel_74/3657823502.py:24: DeprecationWarning: Use torch_xla.sync instead
  xm.mark_step()
  0%|          | 1/306 [00:26<2:14:07, 26.39s/it]

  1%|          | 2/306 [00:43<1:45:12, 20.76s/it]

  1%|▏         | 4/306 [00:43<39:13,  7.79s/it]

  2%|▏         | 6/306 [00:43<20:43,  4.14s/it]

  3%|▎         | 8/306 [00:43<12:27,  2.51s/it]

  3%|▎         | 10/306 [00:43<07:59,  1.62s/it]

  4%|▍         | 12/306 [00:43<05:20,  1.09s/it]

  5%|▍         | 14/306 [00:44<03:40,  1.32it/s]

  5%|▌         | 16/306 [00:44<02:36,  1.85it/s]

  6%|▌         | 18/306 [00:44<01:53,  2.54it/s]

  7%|▋         | 20/306 [00:44<01:24,  3.39it/s]

  7%|▋         | 22/306 [00:44<01:04,  4.41it/s]

  8%|▊         | 24/306 [00:44<00:50,  5.54it/s]

  8%|▊         | 26/306 [00:45<00:41,  6.76it/s]

  9%|▉         | 28/306 [00:45<00:34,  7.98it/s]

 10%|▉         | 30/306 [00:45<00:30,  9.14it/s]

 10%|█         | 32/306 [00:45<00:26, 10.17it/s]

 11%|█         | 34/306 [00:46<00:47,  5.78it/s]

 12%|█▏        | 36/306 [00:46<00:38,  7.00it/s]

 12%|█▏        | 38/306 [00:46<00:32,  8.20it/s]

 13%|█▎        | 40/306 [00:46<00:28,  9.31it/s]

 14%|█▎        | 42/306 [00:51<03:48,  1.15it/s]

 14%|█▍        | 44/306 [00:52<02:44,  1.59it/s]

 15%|█▌        | 46/306 [00:52<02:00,  2.16it/s]

 16%|█▌        | 48/306 [00:52<01:29,  2.90it/s]

 16%|█▋        | 50/306 [00:56<03:43,  1.15it/s]

 17%|█▋        | 52/306 [00:56<02:40,  1.58it/s]

 18%|█▊        | 54/306 [00:56<01:56,  2.15it/s]

 18%|█▊        | 56/306 [00:56<01:26,  2.88it/s]

 19%|█▉        | 58/306 [01:00<03:31,  1.17it/s]

 20%|█▉        | 60/306 [01:01<02:32,  1.62it/s]

 20%|██        | 62/306 [01:01<01:50,  2.20it/s]

 21%|██        | 64/306 [01:01<01:22,  2.94it/s]

 22%|██▏       | 66/306 [01:05<03:37,  1.10it/s]

 22%|██▏       | 68/306 [01:06<02:36,  1.52it/s]

 23%|██▎       | 70/306 [01:06<01:53,  2.08it/s]

 24%|██▎       | 72/306 [01:06<01:23,  2.79it/s]

 24%|██▍       | 74/306 [01:11<04:06,  1.06s/it]

 25%|██▍       | 76/306 [01:11<02:55,  1.31it/s]

 25%|██▌       | 78/306 [01:12<02:07,  1.79it/s]

 26%|██▌       | 80/306 [01:12<01:33,  2.43it/s]

 27%|██▋       | 82/306 [01:17<03:53,  1.04s/it]

 27%|██▋       | 84/306 [01:17<02:47,  1.33it/s]

 28%|██▊       | 86/306 [01:17<02:00,  1.82it/s]

 29%|██▉       | 88/306 [01:17<01:28,  2.46it/s]

 29%|██▉       | 90/306 [01:23<04:07,  1.15s/it]

 30%|███       | 92/306 [01:23<02:56,  1.21it/s]

 31%|███       | 94/306 [01:23<02:07,  1.67it/s]

 31%|███▏      | 96/306 [01:23<01:32,  2.26it/s]

 32%|███▏      | 98/306 [01:29<03:46,  1.09s/it]

 33%|███▎      | 100/306 [01:29<02:41,  1.28it/s]

 33%|███▎      | 102/306 [01:29<01:56,  1.75it/s]

 34%|███▍      | 104/306 [01:29<01:24,  2.38it/s]

 35%|███▍      | 106/306 [01:35<03:55,  1.18s/it]

 35%|███▌      | 108/306 [01:35<02:47,  1.18it/s]

 36%|███▌      | 110/306 [01:35<02:00,  1.63it/s]

 37%|███▋      | 112/306 [01:35<01:27,  2.22it/s]

 37%|███▋      | 114/306 [01:40<03:30,  1.10s/it]

 38%|███▊      | 116/306 [01:41<02:30,  1.26it/s]

 39%|███▊      | 118/306 [01:41<01:48,  1.74it/s]

 39%|███▉      | 120/306 [01:41<01:19,  2.35it/s]

 40%|███▉      | 122/306 [01:46<03:06,  1.01s/it]

 41%|████      | 124/306 [01:46<02:13,  1.37it/s]

 41%|████      | 126/306 [01:46<01:36,  1.87it/s]

 42%|████▏     | 128/306 [01:46<01:10,  2.52it/s]

 42%|████▏     | 130/306 [01:50<02:23,  1.22it/s]

 43%|████▎     | 132/306 [01:50<01:43,  1.68it/s]

 44%|████▍     | 134/306 [01:50<01:15,  2.28it/s]

 44%|████▍     | 136/306 [01:50<00:55,  3.04it/s]

 45%|████▌     | 138/306 [01:54<02:06,  1.33it/s]

 46%|████▌     | 140/306 [01:54<01:30,  1.82it/s]

 46%|████▋     | 142/306 [01:54<01:06,  2.46it/s]

 47%|████▋     | 144/306 [01:54<00:49,  3.26it/s]

 48%|████▊     | 146/306 [01:58<01:58,  1.35it/s]

 48%|████▊     | 148/306 [01:58<01:25,  1.85it/s]

 49%|████▉     | 150/306 [01:58<01:02,  2.49it/s]

 50%|████▉     | 152/306 [01:58<00:46,  3.30it/s]

 50%|█████     | 154/306 [02:03<02:23,  1.06it/s]

 51%|█████     | 156/306 [02:03<01:42,  1.46it/s]

 52%|█████▏    | 158/306 [02:03<01:14,  2.00it/s]

 52%|█████▏    | 160/306 [02:03<00:54,  2.69it/s]

 53%|█████▎    | 162/306 [02:08<02:27,  1.03s/it]

 54%|█████▎    | 164/306 [02:09<01:45,  1.35it/s]

 54%|█████▍    | 166/306 [02:09<01:15,  1.85it/s]

 55%|█████▍    | 168/306 [02:09<00:55,  2.50it/s]

 56%|█████▌    | 170/306 [02:14<02:24,  1.06s/it]

 56%|█████▌    | 172/306 [02:14<01:42,  1.31it/s]

 57%|█████▋    | 174/306 [02:14<01:13,  1.79it/s]

 58%|█████▊    | 176/306 [02:15<00:53,  2.43it/s]

 58%|█████▊    | 178/306 [02:20<02:22,  1.11s/it]

 59%|█████▉    | 180/306 [02:20<01:40,  1.25it/s]

 59%|█████▉    | 182/306 [02:20<01:12,  1.72it/s]

 60%|██████    | 184/306 [02:21<00:52,  2.33it/s]

 61%|██████    | 186/306 [02:26<02:13,  1.12s/it]

 61%|██████▏   | 188/306 [02:26<01:34,  1.25it/s]

 62%|██████▏   | 190/306 [02:26<01:07,  1.71it/s]

 63%|██████▎   | 192/306 [02:26<00:49,  2.33it/s]

 63%|██████▎   | 194/306 [02:32<02:05,  1.12s/it]

 64%|██████▍   | 196/306 [02:32<01:28,  1.24it/s]

 65%|██████▍   | 198/306 [02:32<01:03,  1.71it/s]

 65%|██████▌   | 200/306 [02:32<00:45,  2.32it/s]

 66%|██████▌   | 202/306 [02:38<01:56,  1.12s/it]

 67%|██████▋   | 204/306 [02:38<01:22,  1.24it/s]

 67%|██████▋   | 206/306 [02:38<00:58,  1.71it/s]

 68%|██████▊   | 208/306 [02:38<00:42,  2.32it/s]

 69%|██████▊   | 210/306 [02:43<01:45,  1.10s/it]

 69%|██████▉   | 212/306 [02:44<01:14,  1.26it/s]

 70%|██████▉   | 214/306 [02:44<00:53,  1.73it/s]

 71%|███████   | 216/306 [02:44<00:38,  2.35it/s]

 71%|███████   | 218/306 [02:49<01:35,  1.08s/it]

 72%|███████▏  | 220/306 [02:49<01:06,  1.28it/s]

 73%|███████▎  | 222/306 [02:49<00:47,  1.76it/s]

 73%|███████▎  | 224/306 [02:50<00:34,  2.39it/s]

 74%|███████▍  | 226/306 [02:55<01:31,  1.14s/it]

 75%|███████▍  | 228/306 [02:55<01:04,  1.22it/s]

 75%|███████▌  | 230/306 [02:56<00:45,  1.68it/s]

 76%|███████▌  | 232/306 [02:56<00:32,  2.28it/s]

 76%|███████▋  | 234/306 [03:01<01:17,  1.07s/it]

 77%|███████▋  | 236/306 [03:01<00:54,  1.29it/s]

 78%|███████▊  | 238/306 [03:01<00:38,  1.77it/s]

 78%|███████▊  | 240/306 [03:01<00:27,  2.40it/s]

 79%|███████▉  | 242/306 [03:07<01:10,  1.10s/it]

 80%|███████▉  | 244/306 [03:07<00:49,  1.26it/s]

 80%|████████  | 246/306 [03:07<00:34,  1.73it/s]

 81%|████████  | 248/306 [03:07<00:24,  2.34it/s]

 82%|████████▏ | 250/306 [03:11<00:52,  1.07it/s]

 82%|████████▏ | 252/306 [03:11<00:36,  1.47it/s]

 83%|████████▎ | 254/306 [03:12<00:25,  2.01it/s]

 84%|████████▎ | 256/306 [03:12<00:18,  2.71it/s]

 84%|████████▍ | 258/306 [03:15<00:38,  1.24it/s]

 85%|████████▍ | 260/306 [03:16<00:26,  1.71it/s]

 86%|████████▌ | 262/306 [03:16<00:19,  2.31it/s]

 86%|████████▋ | 264/306 [03:16<00:13,  3.08it/s]

 87%|████████▋ | 266/306 [03:20<00:31,  1.28it/s]

 88%|████████▊ | 268/306 [03:20<00:21,  1.76it/s]

 88%|████████▊ | 270/306 [03:20<00:15,  2.37it/s]

 89%|████████▉ | 272/306 [03:20<00:10,  3.15it/s]

 90%|████████▉ | 274/306 [03:24<00:24,  1.28it/s]

 90%|█████████ | 276/306 [03:24<00:17,  1.76it/s]

 91%|█████████ | 278/306 [03:24<00:11,  2.39it/s]

 92%|█████████▏| 280/306 [03:24<00:08,  3.17it/s]

 92%|█████████▏| 282/306 [03:28<00:18,  1.28it/s]

 93%|█████████▎| 284/306 [03:28<00:12,  1.76it/s]

 93%|█████████▎| 286/306 [03:28<00:08,  2.38it/s]

 94%|█████████▍| 288/306 [03:28<00:05,  3.17it/s]

 95%|█████████▍| 290/306 [03:32<00:12,  1.31it/s]

 95%|█████████▌| 292/306 [03:32<00:07,  1.79it/s]

 96%|█████████▌| 294/306 [03:32<00:04,  2.43it/s]

 97%|█████████▋| 296/306 [03:32<00:03,  3.22it/s]

 97%|█████████▋| 298/306 [03:36<00:06,  1.31it/s]

 98%|█████████▊| 300/306 [03:36<00:03,  1.79it/s]

 99%|█████████▊| 302/306 [03:36<00:01,  2.43it/s]

 99%|█████████▉| 304/306 [03:36<00:00,  3.22it/s]

100%|██████████| 306/306 [03:37<00:00,  3.26it/s]

100%|██████████| 306/306 [03:37<00:00,  1.41it/s]

/tmp/ipykernel_74/1073665200.py:20: DeprecationWarning: Use torch_xla.sync instead
  xm.mark_step()

resnet Epoch 0 loss 2.9193 val_acc 0.4406

Saved best resnet to /kaggle/working/writer_resnet_best.pth

  0%|          | 0/306 [00:00<?, ?it/s]

  0%|          | 1/306 [00:02<14:56,  2.94s/it]

  1%|          | 3/306 [00:03<04:07,  1.23it/s]

  2%|▏         | 5/306 [00:03<02:10,  2.31it/s]

  2%|▏         | 7/306 [00:03<01:24,  3.55it/s]

  3%|▎         | 9/306 [00:04<02:20,  2.11it/s]

  4%|▎         | 11/306 [00:05<01:38,  3.00it/s]

  4%|▍         | 13/306 [00:05<01:12,  4.05it/s]

  5%|▍         | 15/306 [00:05<00:55,  5.26it/s]

  6%|▌         | 17/306 [00:06<01:46,  2.70it/s]

  6%|▌         | 19/306 [00:07<01:19,  3.61it/s]

  7%|▋         | 21/306 [00:07<01:01,  4.67it/s]

  8%|▊         | 23/306 [00:07<00:48,  5.86it/s]

  8%|▊         | 25/306 [00:08<01:39,  2.82it/s]

  9%|▉         | 27/306 [00:09<01:15,  3.72it/s]

  9%|▉         | 29/306 [00:09<00:57,  4.78it/s]

 10%|█         | 31/306 [00:09<00:46,  5.95it/s]

 11%|█         | 33/306 [00:10<01:35,  2.85it/s]

 11%|█▏        | 35/306 [00:11<01:12,  3.75it/s]

 12%|█▏        | 37/306 [00:11<00:56,  4.80it/s]

 13%|█▎        | 39/306 [00:11<00:44,  5.97it/s]

 13%|█▎        | 41/306 [00:12<01:31,  2.90it/s]

 14%|█▍        | 43/306 [00:12<01:09,  3.80it/s]

 15%|█▍        | 45/306 [00:13<00:53,  4.86it/s]

 15%|█▌        | 47/306 [00:13<00:42,  6.04it/s]

 16%|█▌        | 49/306 [00:14<01:30,  2.84it/s]

 17%|█▋        | 51/306 [00:14<01:08,  3.73it/s]

 17%|█▋        | 53/306 [00:15<00:53,  4.77it/s]

 18%|█▊        | 55/306 [00:15<00:42,  5.93it/s]

 19%|█▊        | 57/306 [00:16<01:27,  2.84it/s]

 19%|█▉        | 59/306 [00:16<01:06,  3.73it/s]

 20%|█▉        | 61/306 [00:17<00:51,  4.77it/s]

 21%|██        | 63/306 [00:17<00:41,  5.92it/s]

 21%|██        | 65/306 [00:18<01:25,  2.81it/s]

 22%|██▏       | 67/306 [00:19<01:04,  3.69it/s]

 23%|██▎       | 69/306 [00:19<00:50,  4.72it/s]

 23%|██▎       | 71/306 [00:19<00:39,  5.88it/s]

 24%|██▍       | 73/306 [00:20<01:21,  2.85it/s]

 25%|██▍       | 75/306 [00:20<01:01,  3.74it/s]

 25%|██▌       | 77/306 [00:21<00:47,  4.79it/s]

 26%|██▌       | 79/306 [00:21<00:38,  5.92it/s]

 26%|██▋       | 81/306 [00:22<01:18,  2.85it/s]

 27%|██▋       | 83/306 [00:22<00:59,  3.75it/s]

 28%|██▊       | 85/306 [00:23<00:46,  4.80it/s]

 28%|██▊       | 87/306 [00:23<00:36,  5.96it/s]

 29%|██▉       | 89/306 [00:24<01:16,  2.82it/s]

 30%|██▉       | 91/306 [00:24<00:58,  3.70it/s]

 30%|███       | 93/306 [00:25<00:44,  4.75it/s]

 31%|███       | 95/306 [00:25<00:35,  5.91it/s]

 32%|███▏      | 97/306 [00:26<01:13,  2.86it/s]

 32%|███▏      | 99/306 [00:26<00:55,  3.73it/s]

 33%|███▎      | 101/306 [00:27<00:42,  4.77it/s]

 34%|███▎      | 103/306 [00:27<00:34,  5.92it/s]

 34%|███▍      | 105/306 [00:28<01:11,  2.82it/s]

 35%|███▍      | 107/306 [00:28<00:53,  3.71it/s]

 36%|███▌      | 109/306 [00:29<00:41,  4.76it/s]

 36%|███▋      | 111/306 [00:29<00:32,  5.92it/s]

 37%|███▋      | 113/306 [00:30<01:08,  2.84it/s]

 38%|███▊      | 115/306 [00:30<00:51,  3.73it/s]

 38%|███▊      | 117/306 [00:31<00:39,  4.78it/s]

 39%|███▉      | 119/306 [00:31<00:31,  5.95it/s]

 40%|███▉      | 121/306 [00:32<01:05,  2.83it/s]

 40%|████      | 123/306 [00:32<00:49,  3.71it/s]

 41%|████      | 125/306 [00:33<00:38,  4.75it/s]

 42%|████▏     | 127/306 [00:33<00:30,  5.91it/s]

 42%|████▏     | 129/306 [00:34<01:02,  2.82it/s]

 43%|████▎     | 131/306 [00:34<00:47,  3.71it/s]

 43%|████▎     | 133/306 [00:35<00:36,  4.76it/s]

 44%|████▍     | 135/306 [00:35<00:28,  5.94it/s]

 45%|████▍     | 137/306 [00:36<00:58,  2.87it/s]

 45%|████▌     | 139/306 [00:36<00:44,  3.77it/s]

 46%|████▌     | 141/306 [00:37<00:34,  4.83it/s]

 47%|████▋     | 143/306 [00:37<00:27,  5.99it/s]

 47%|████▋     | 145/306 [00:38<00:59,  2.70it/s]

 48%|████▊     | 147/306 [00:39<00:44,  3.56it/s]

 49%|████▊     | 149/306 [00:39<00:34,  4.58it/s]

 49%|████▉     | 151/306 [00:39<00:27,  5.74it/s]

 50%|█████     | 153/306 [00:40<00:55,  2.75it/s]

 51%|█████     | 155/306 [00:41<00:41,  3.62it/s]

 51%|█████▏    | 157/306 [00:41<00:32,  4.65it/s]

 52%|█████▏    | 159/306 [00:41<00:25,  5.81it/s]

 53%|█████▎    | 161/306 [00:42<00:51,  2.81it/s]

 53%|█████▎    | 163/306 [00:43<00:38,  3.70it/s]

 54%|█████▍    | 165/306 [00:43<00:29,  4.75it/s]

 55%|█████▍    | 167/306 [00:43<00:23,  5.90it/s]

 55%|█████▌    | 169/306 [00:45<00:50,  2.72it/s]

 56%|█████▌    | 171/306 [00:45<00:37,  3.58it/s]

 57%|█████▋    | 173/306 [00:45<00:28,  4.61it/s]

 57%|█████▋    | 175/306 [00:45<00:22,  5.77it/s]

 58%|█████▊    | 177/306 [00:47<00:46,  2.78it/s]

 58%|█████▊    | 179/306 [00:47<00:34,  3.66it/s]

 59%|█████▉    | 181/306 [00:47<00:26,  4.70it/s]

 60%|█████▉    | 183/306 [00:47<00:20,  5.86it/s]

 60%|██████    | 185/306 [00:49<00:44,  2.73it/s]

 61%|██████    | 187/306 [00:49<00:33,  3.60it/s]

 62%|██████▏   | 189/306 [00:49<00:25,  4.63it/s]

 62%|██████▏   | 191/306 [00:49<00:19,  5.79it/s]

 63%|██████▎   | 193/306 [00:51<00:41,  2.75it/s]

 64%|██████▎   | 195/306 [00:51<00:30,  3.63it/s]

 64%|██████▍   | 197/306 [00:51<00:23,  4.66it/s]

 65%|██████▌   | 199/306 [00:51<00:18,  5.83it/s]

 66%|██████▌   | 201/306 [00:53<00:37,  2.80it/s]

 66%|██████▋   | 203/306 [00:53<00:27,  3.68it/s]

 67%|██████▋   | 205/306 [00:53<00:21,  4.74it/s]

 68%|██████▊   | 207/306 [00:53<00:16,  5.92it/s]

 68%|██████▊   | 209/306 [00:55<00:34,  2.82it/s]

 69%|██████▉   | 211/306 [00:55<00:25,  3.70it/s]

 70%|██████▉   | 213/306 [00:55<00:19,  4.73it/s]

 70%|███████   | 215/306 [00:55<00:15,  5.82it/s]

 71%|███████   | 217/306 [00:57<00:32,  2.76it/s]

 72%|███████▏  | 219/306 [00:57<00:24,  3.62it/s]

 72%|███████▏  | 221/306 [00:57<00:18,  4.64it/s]

 73%|███████▎  | 223/306 [00:57<00:14,  5.80it/s]

 74%|███████▎  | 225/306 [00:59<00:29,  2.79it/s]

 74%|███████▍  | 227/306 [00:59<00:21,  3.66it/s]

 75%|███████▍  | 229/306 [00:59<00:16,  4.71it/s]

 75%|███████▌  | 231/306 [00:59<00:12,  5.86it/s]

 76%|███████▌  | 233/306 [01:01<00:27,  2.65it/s]

 77%|███████▋  | 235/306 [01:01<00:20,  3.46it/s]

 77%|███████▋  | 237/306 [01:01<00:15,  4.45it/s]

 78%|███████▊  | 239/306 [01:01<00:12,  5.57it/s]

 79%|███████▉  | 241/306 [01:03<00:23,  2.73it/s]

 79%|███████▉  | 243/306 [01:03<00:17,  3.59it/s]

 80%|████████  | 245/306 [01:03<00:13,  4.63it/s]

 81%|████████  | 247/306 [01:03<00:10,  5.80it/s]

 81%|████████▏ | 249/306 [01:05<00:20,  2.76it/s]

 82%|████████▏ | 251/306 [01:05<00:15,  3.62it/s]

 83%|████████▎ | 253/306 [01:05<00:11,  4.65it/s]

 83%|████████▎ | 255/306 [01:06<00:08,  5.80it/s]

 84%|████████▍ | 257/306 [01:07<00:17,  2.74it/s]

 85%|████████▍ | 259/306 [01:07<00:13,  3.60it/s]

 85%|████████▌ | 261/306 [01:07<00:09,  4.61it/s]

 86%|████████▌ | 263/306 [01:08<00:07,  5.76it/s]

 87%|████████▋ | 265/306 [01:09<00:14,  2.75it/s]

 87%|████████▋ | 267/306 [01:09<00:10,  3.62it/s]

 88%|████████▊ | 269/306 [01:10<00:07,  4.66it/s]

 89%|████████▊ | 271/306 [01:10<00:06,  5.82it/s]

 89%|████████▉ | 273/306 [01:11<00:12,  2.72it/s]

 90%|████████▉ | 275/306 [01:11<00:08,  3.58it/s]

 91%|█████████ | 277/306 [01:12<00:06,  4.62it/s]

 91%|█████████ | 279/306 [01:12<00:04,  5.79it/s]

 92%|█████████▏| 281/306 [01:13<00:09,  2.68it/s]

 92%|█████████▏| 283/306 [01:14<00:06,  3.54it/s]

 93%|█████████▎| 285/306 [01:14<00:04,  4.56it/s]

 94%|█████████▍| 287/306 [01:14<00:03,  5.72it/s]

 94%|█████████▍| 289/306 [01:16<00:06,  2.67it/s]

 95%|█████████▌| 291/306 [01:16<00:04,  3.52it/s]

 96%|█████████▌| 293/306 [01:16<00:02,  4.53it/s]

 96%|█████████▋| 295/306 [01:16<00:01,  5.66it/s]

 97%|█████████▋| 297/306 [01:18<00:03,  2.75it/s]

 98%|█████████▊| 299/306 [01:18<00:01,  3.61it/s]

 98%|█████████▊| 301/306 [01:18<00:01,  4.61it/s]

 99%|█████████▉| 303/306 [01:18<00:00,  5.71it/s]

100%|█████████▉| 305/306 [01:18<00:00,  6.02it/s]

100%|██████████| 306/306 [01:18<00:00,  3.88it/s]

resnet Epoch 1 loss 2.1358 val_acc 0.5548

Saved best resnet to /kaggle/working/writer_resnet_best.pth

  0%|          | 0/306 [00:00<?, ?it/s]

  0%|          | 1/306 [00:02<15:14,  3.00s/it]

  1%|          | 3/306 [00:03<04:11,  1.20it/s]

  2%|▏         | 5/306 [00:03<02:12,  2.27it/s]

  2%|▏         | 7/306 [00:03<01:25,  3.50it/s]

  3%|▎         | 9/306 [00:04<02:17,  2.16it/s]

  4%|▎         | 11/306 [00:05<01:36,  3.05it/s]

  4%|▍         | 13/306 [00:05<01:11,  4.12it/s]

  5%|▍         | 15/306 [00:05<00:54,  5.33it/s]

  6%|▌         | 17/306 [00:06<01:45,  2.74it/s]

  6%|▌         | 19/306 [00:07<01:18,  3.65it/s]

  7%|▋         | 21/306 [00:07<01:00,  4.72it/s]

  8%|▊         | 23/306 [00:07<00:47,  5.91it/s]

  8%|▊         | 25/306 [00:08<01:37,  2.87it/s]

  9%|▉         | 27/306 [00:08<01:13,  3.78it/s]

  9%|▉         | 29/306 [00:09<00:57,  4.83it/s]

 10%|█         | 31/306 [00:09<00:45,  6.02it/s]

 11%|█         | 33/306 [00:10<01:35,  2.86it/s]

 11%|█▏        | 35/306 [00:10<01:12,  3.76it/s]

 12%|█▏        | 37/306 [00:11<00:55,  4.82it/s]

 13%|█▎        | 39/306 [00:11<00:44,  6.00it/s]

 13%|█▎        | 41/306 [00:12<01:32,  2.85it/s]

 14%|█▍        | 43/306 [00:12<01:10,  3.74it/s]

 15%|█▍        | 45/306 [00:13<00:54,  4.79it/s]

 15%|█▌        | 47/306 [00:13<00:43,  5.97it/s]

 16%|█▌        | 49/306 [00:14<01:30,  2.83it/s]

 17%|█▋        | 51/306 [00:14<01:08,  3.72it/s]

 17%|█▋        | 53/306 [00:15<00:52,  4.78it/s]

 18%|█▊        | 55/306 [00:15<00:42,  5.95it/s]

 19%|█▊        | 57/306 [00:16<01:28,  2.83it/s]

 19%|█▉        | 59/306 [00:16<01:06,  3.72it/s]

 20%|█▉        | 61/306 [00:17<00:51,  4.77it/s]

 21%|██        | 63/306 [00:17<00:40,  5.94it/s]

 21%|██        | 65/306 [00:18<01:24,  2.85it/s]

 22%|██▏       | 67/306 [00:18<01:04,  3.73it/s]

 23%|██▎       | 69/306 [00:19<00:49,  4.79it/s]

 23%|██▎       | 71/306 [00:19<00:39,  5.96it/s]

 24%|██▍       | 73/306 [00:20<01:21,  2.85it/s]

 25%|██▍       | 75/306 [00:20<01:01,  3.74it/s]

 25%|██▌       | 77/306 [00:21<00:47,  4.80it/s]

 26%|██▌       | 79/306 [00:21<00:37,  5.98it/s]

 26%|██▋       | 81/306 [00:22<01:18,  2.85it/s]

 27%|██▋       | 83/306 [00:22<00:59,  3.74it/s]

 28%|██▊       | 85/306 [00:23<00:46,  4.79it/s]

 28%|██▊       | 87/306 [00:23<00:36,  5.96it/s]

 29%|██▉       | 89/306 [00:24<01:15,  2.86it/s]

 30%|██▉       | 91/306 [00:24<00:57,  3.75it/s]

 30%|███       | 93/306 [00:25<00:44,  4.81it/s]

 31%|███       | 95/306 [00:25<00:35,  5.97it/s]

 32%|███▏      | 97/306 [00:26<01:13,  2.85it/s]

 32%|███▏      | 99/306 [00:26<00:55,  3.74it/s]

 33%|███▎      | 101/306 [00:27<00:42,  4.79it/s]

 34%|███▎      | 103/306 [00:27<00:33,  5.97it/s]

 34%|███▍      | 105/306 [00:28<01:10,  2.84it/s]

 35%|███▍      | 107/306 [00:28<00:53,  3.73it/s]

 36%|███▌      | 109/306 [00:29<00:41,  4.78it/s]

 36%|███▋      | 111/306 [00:29<00:32,  5.95it/s]

 37%|███▋      | 113/306 [00:30<01:06,  2.90it/s]

 38%|███▊      | 115/306 [00:30<00:50,  3.80it/s]

 38%|███▊      | 117/306 [00:30<00:38,  4.86it/s]

 39%|███▉      | 119/306 [00:31<00:31,  6.01it/s]

 40%|███▉      | 121/306 [00:32<01:04,  2.87it/s]

 40%|████      | 123/306 [00:32<00:48,  3.76it/s]

 41%|████      | 125/306 [00:32<00:37,  4.82it/s]

 42%|████▏     | 127/306 [00:33<00:29,  5.99it/s]

 42%|████▏     | 129/306 [00:34<01:02,  2.83it/s]

 43%|████▎     | 131/306 [00:34<00:47,  3.71it/s]

 43%|████▎     | 133/306 [00:34<00:36,  4.76it/s]

 44%|████▍     | 135/306 [00:35<00:28,  5.93it/s]

 45%|████▍     | 137/306 [00:36<00:57,  2.92it/s]

 45%|████▌     | 139/306 [00:36<00:43,  3.82it/s]

 46%|████▌     | 141/306 [00:36<00:33,  4.87it/s]

 47%|████▋     | 143/306 [00:37<00:27,  6.02it/s]

 47%|████▋     | 145/306 [00:38<00:54,  2.95it/s]

 48%|████▊     | 147/306 [00:38<00:41,  3.86it/s]

 49%|████▊     | 149/306 [00:38<00:31,  4.93it/s]

 49%|████▉     | 151/306 [00:38<00:25,  6.11it/s]

 50%|█████     | 153/306 [00:40<00:52,  2.92it/s]

 51%|█████     | 155/306 [00:40<00:39,  3.82it/s]

 51%|█████▏    | 157/306 [00:40<00:30,  4.86it/s]

 52%|█████▏    | 159/306 [00:40<00:24,  6.03it/s]

 53%|█████▎    | 161/306 [00:42<00:49,  2.96it/s]

 53%|█████▎    | 163/306 [00:42<00:37,  3.85it/s]

 54%|█████▍    | 165/306 [00:42<00:28,  4.90it/s]

 55%|█████▍    | 167/306 [00:42<00:22,  6.06it/s]

 55%|█████▌    | 169/306 [00:44<00:46,  2.94it/s]

 56%|█████▌    | 171/306 [00:44<00:35,  3.84it/s]

 57%|█████▋    | 173/306 [00:44<00:27,  4.91it/s]

 57%|█████▋    | 175/306 [00:44<00:21,  6.07it/s]

 58%|█████▊    | 177/306 [00:46<00:45,  2.86it/s]

 58%|█████▊    | 179/306 [00:46<00:33,  3.74it/s]

 59%|█████▉    | 181/306 [00:46<00:26,  4.79it/s]

 60%|█████▉    | 183/306 [00:46<00:20,  5.94it/s]

 60%|██████    | 185/306 [00:48<00:41,  2.92it/s]

 61%|██████    | 187/306 [00:48<00:31,  3.81it/s]

 62%|██████▏   | 189/306 [00:48<00:24,  4.86it/s]

 62%|██████▏   | 191/306 [00:48<00:19,  6.02it/s]

 63%|██████▎   | 193/306 [00:50<00:39,  2.85it/s]

 64%|██████▎   | 195/306 [00:50<00:29,  3.74it/s]

 64%|██████▍   | 197/306 [00:50<00:22,  4.80it/s]

 65%|██████▌   | 199/306 [00:50<00:17,  5.98it/s]

 66%|██████▌   | 201/306 [00:52<00:36,  2.86it/s]

 66%|██████▋   | 203/306 [00:52<00:27,  3.75it/s]

 67%|██████▋   | 205/306 [00:52<00:21,  4.80it/s]

 68%|██████▊   | 207/306 [00:52<00:16,  5.96it/s]

 68%|██████▊   | 209/306 [00:54<00:33,  2.85it/s]

 69%|██████▉   | 211/306 [00:54<00:25,  3.73it/s]

 70%|██████▉   | 213/306 [00:54<00:19,  4.78it/s]

 70%|███████   | 215/306 [00:54<00:15,  5.92it/s]

 71%|███████   | 217/306 [00:56<00:30,  2.87it/s]

 72%|███████▏  | 219/306 [00:56<00:23,  3.77it/s]

 72%|███████▏  | 221/306 [00:56<00:17,  4.83it/s]

 73%|███████▎  | 223/306 [00:56<00:13,  6.00it/s]

 74%|███████▎  | 225/306 [00:58<00:28,  2.88it/s]

 74%|███████▍  | 227/306 [00:58<00:20,  3.77it/s]

 75%|███████▍  | 229/306 [00:58<00:15,  4.82it/s]

 75%|███████▌  | 231/306 [00:58<00:12,  6.00it/s]

 76%|███████▌  | 233/306 [01:00<00:25,  2.84it/s]

 77%|███████▋  | 235/306 [01:00<00:19,  3.73it/s]

 77%|███████▋  | 237/306 [01:00<00:14,  4.78it/s]

 78%|███████▊  | 239/306 [01:00<00:11,  5.94it/s]

 79%|███████▉  | 241/306 [01:02<00:22,  2.90it/s]

 79%|███████▉  | 243/306 [01:02<00:16,  3.80it/s]

 80%|████████  | 245/306 [01:02<00:12,  4.87it/s]

 81%|████████  | 247/306 [01:02<00:09,  6.02it/s]

 81%|████████▏ | 249/306 [01:04<00:19,  2.86it/s]

 82%|████████▏ | 251/306 [01:04<00:14,  3.74it/s]

 83%|████████▎ | 253/306 [01:04<00:11,  4.79it/s]

 83%|████████▎ | 255/306 [01:04<00:08,  5.96it/s]

 84%|████████▍ | 257/306 [01:06<00:17,  2.86it/s]

 85%|████████▍ | 259/306 [01:06<00:12,  3.75it/s]

 85%|████████▌ | 261/306 [01:06<00:09,  4.80it/s]

 86%|████████▌ | 263/306 [01:06<00:07,  5.97it/s]

 87%|████████▋ | 265/306 [01:08<00:14,  2.87it/s]

 87%|████████▋ | 267/306 [01:08<00:10,  3.77it/s]

 88%|████████▊ | 269/306 [01:08<00:07,  4.82it/s]

 89%|████████▊ | 271/306 [01:08<00:05,  5.99it/s]

 89%|████████▉ | 273/306 [01:10<00:11,  2.89it/s]

 90%|████████▉ | 275/306 [01:10<00:08,  3.78it/s]

 91%|█████████ | 277/306 [01:10<00:05,  4.84it/s]

 91%|█████████ | 279/306 [01:10<00:04,  6.01it/s]

 92%|█████████▏| 281/306 [01:12<00:08,  2.88it/s]

 92%|█████████▏| 283/306 [01:12<00:06,  3.77it/s]

 93%|█████████▎| 285/306 [01:12<00:04,  4.83it/s]

 94%|█████████▍| 287/306 [01:12<00:03,  6.00it/s]

 94%|█████████▍| 289/306 [01:14<00:06,  2.82it/s]

 95%|█████████▌| 291/306 [01:14<00:04,  3.70it/s]

 96%|█████████▌| 293/306 [01:14<00:02,  4.75it/s]

 96%|█████████▋| 295/306 [01:14<00:01,  5.92it/s]

 97%|█████████▋| 297/306 [01:16<00:03,  2.69it/s]

 98%|█████████▊| 299/306 [01:16<00:01,  3.55it/s]

 98%|█████████▊| 301/306 [01:16<00:01,  4.58it/s]

 99%|█████████▉| 303/306 [01:16<00:00,  5.73it/s]

100%|█████████▉| 305/306 [01:16<00:00,  6.26it/s]

100%|██████████| 306/306 [01:16<00:00,  3.97it/s]

resnet Epoch 2 loss 1.8383 val_acc 0.6522

Saved best resnet to /kaggle/working/writer_resnet_best.pth

  0%|          | 0/306 [00:00<?, ?it/s]

  0%|          | 1/306 [00:02<14:47,  2.91s/it]

  1%|          | 3/306 [00:03<04:05,  1.23it/s]

  2%|▏         | 5/306 [00:03<02:10,  2.31it/s]

  2%|▏         | 7/306 [00:03<01:24,  3.56it/s]

  3%|▎         | 9/306 [00:04<02:13,  2.23it/s]

  4%|▎         | 11/306 [00:04<01:33,  3.16it/s]

  4%|▍         | 13/306 [00:05<01:08,  4.25it/s]

  5%|▍         | 15/306 [00:05<00:53,  5.46it/s]

  6%|▌         | 17/306 [00:06<01:47,  2.69it/s]

  6%|▌         | 19/306 [00:06<01:20,  3.58it/s]

  7%|▋         | 21/306 [00:07<01:01,  4.63it/s]

  8%|▊         | 23/306 [00:07<00:48,  5.81it/s]

  8%|▊         | 25/306 [00:08<01:38,  2.85it/s]

  9%|▉         | 27/306 [00:08<01:14,  3.74it/s]

  9%|▉         | 29/306 [00:09<00:57,  4.79it/s]

 10%|█         | 31/306 [00:09<00:46,  5.95it/s]

 11%|█         | 33/306 [00:10<01:32,  2.96it/s]

 11%|█▏        | 35/306 [00:10<01:09,  3.87it/s]

 12%|█▏        | 37/306 [00:10<00:54,  4.93it/s]

 13%|█▎        | 39/306 [00:11<00:43,  6.10it/s]

 13%|█▎        | 41/306 [00:12<01:29,  2.96it/s]

 14%|█▍        | 43/306 [00:12<01:08,  3.86it/s]

 15%|█▍        | 45/306 [00:12<00:53,  4.88it/s]

 15%|█▌        | 47/306 [00:13<00:42,  6.02it/s]

 16%|█▌        | 49/306 [00:14<01:28,  2.89it/s]

 17%|█▋        | 51/306 [00:14<01:07,  3.80it/s]

 17%|█▋        | 53/306 [00:14<00:52,  4.85it/s]

 18%|█▊        | 55/306 [00:15<00:41,  6.01it/s]

 19%|█▊        | 57/306 [00:16<01:25,  2.93it/s]

 19%|█▉        | 59/306 [00:16<01:04,  3.83it/s]

 20%|█▉        | 61/306 [00:16<00:50,  4.88it/s]

 21%|██        | 63/306 [00:16<00:40,  6.07it/s]

 21%|██        | 65/306 [00:18<01:22,  2.91it/s]

 22%|██▏       | 67/306 [00:18<01:02,  3.80it/s]

 23%|██▎       | 69/306 [00:18<00:49,  4.84it/s]

 23%|██▎       | 71/306 [00:18<00:39,  5.99it/s]

 24%|██▍       | 73/306 [00:20<01:22,  2.83it/s]

 25%|██▍       | 75/306 [00:20<01:02,  3.72it/s]

 25%|██▌       | 77/306 [00:20<00:48,  4.77it/s]

 26%|██▌       | 79/306 [00:20<00:38,  5.95it/s]

 26%|██▋       | 81/306 [00:22<01:18,  2.88it/s]

 27%|██▋       | 83/306 [00:22<00:58,  3.78it/s]

 28%|██▊       | 85/306 [00:22<00:45,  4.85it/s]

 28%|██▊       | 87/306 [00:22<00:36,  6.04it/s]

 29%|██▉       | 89/306 [00:24<01:15,  2.86it/s]

 30%|██▉       | 91/306 [00:24<00:57,  3.74it/s]

 30%|███       | 93/306 [00:24<00:44,  4.77it/s]

 31%|███       | 95/306 [00:24<00:35,  5.92it/s]

 32%|███▏      | 97/306 [00:26<01:13,  2.84it/s]

 32%|███▏      | 99/306 [00:26<00:55,  3.74it/s]

 33%|███▎      | 101/306 [00:26<00:42,  4.79it/s]

 34%|███▎      | 103/306 [00:26<00:34,  5.95it/s]

 34%|███▍      | 105/306 [00:28<01:09,  2.89it/s]

 35%|███▍      | 107/306 [00:28<00:52,  3.79it/s]

 36%|███▌      | 109/306 [00:28<00:40,  4.86it/s]

 36%|███▋      | 111/306 [00:28<00:32,  6.05it/s]

 37%|███▋      | 113/306 [00:30<01:06,  2.91it/s]

 38%|███▊      | 115/306 [00:30<00:50,  3.81it/s]

 38%|███▊      | 117/306 [00:30<00:38,  4.85it/s]

 39%|███▉      | 119/306 [00:30<00:31,  6.01it/s]

 40%|███▉      | 121/306 [00:32<01:02,  2.94it/s]

 40%|████      | 123/306 [00:32<00:47,  3.86it/s]

 41%|████      | 125/306 [00:32<00:36,  4.93it/s]

 42%|████▏     | 127/306 [00:32<00:29,  6.11it/s]

 42%|████▏     | 129/306 [00:34<00:59,  2.96it/s]

 43%|████▎     | 131/306 [00:34<00:45,  3.88it/s]

 43%|████▎     | 133/306 [00:34<00:34,  4.95it/s]

 44%|████▍     | 135/306 [00:34<00:27,  6.15it/s]

 45%|████▍     | 137/306 [00:36<00:59,  2.84it/s]

 45%|████▌     | 139/306 [00:36<00:45,  3.71it/s]

 46%|████▌     | 141/306 [00:36<00:34,  4.75it/s]

 47%|████▋     | 143/306 [00:36<00:27,  5.82it/s]

 47%|████▋     | 145/306 [00:38<00:56,  2.85it/s]

 48%|████▊     | 147/306 [00:38<00:42,  3.73it/s]

 49%|████▊     | 149/306 [00:38<00:32,  4.79it/s]

 49%|████▉     | 151/306 [00:38<00:25,  5.96it/s]

 50%|█████     | 153/306 [00:40<00:52,  2.91it/s]

 51%|█████     | 155/306 [00:40<00:39,  3.82it/s]

 51%|█████▏    | 157/306 [00:40<00:30,  4.89it/s]

 52%|█████▏    | 159/306 [00:40<00:24,  6.07it/s]

 53%|█████▎    | 161/306 [00:42<00:51,  2.84it/s]

 53%|█████▎    | 163/306 [00:42<00:38,  3.74it/s]

 54%|█████▍    | 165/306 [00:42<00:29,  4.77it/s]

 55%|█████▍    | 167/306 [00:42<00:23,  5.95it/s]

 55%|█████▌    | 169/306 [00:44<00:56,  2.44it/s]

 56%|█████▌    | 171/306 [00:44<00:41,  3.24it/s]

 57%|█████▋    | 173/306 [00:44<00:31,  4.21it/s]

 57%|█████▋    | 175/306 [00:44<00:24,  5.34it/s]

 58%|█████▊    | 177/306 [00:46<00:47,  2.72it/s]

 58%|█████▊    | 179/306 [00:46<00:35,  3.57it/s]

 59%|█████▉    | 181/306 [00:46<00:27,  4.60it/s]

 60%|█████▉    | 183/306 [00:47<00:21,  5.74it/s]

 60%|██████    | 185/306 [00:48<00:42,  2.82it/s]

 61%|██████    | 187/306 [00:48<00:32,  3.70it/s]

 62%|██████▏   | 189/306 [00:48<00:24,  4.75it/s]

 62%|██████▏   | 191/306 [00:48<00:19,  5.91it/s]

 63%|██████▎   | 193/306 [00:50<00:40,  2.82it/s]

 64%|██████▎   | 195/306 [00:50<00:29,  3.71it/s]

 64%|██████▍   | 197/306 [00:50<00:22,  4.75it/s]

 65%|██████▌   | 199/306 [00:51<00:18,  5.91it/s]

 66%|██████▌   | 201/306 [00:52<00:37,  2.82it/s]

 66%|██████▋   | 203/306 [00:52<00:27,  3.71it/s]

 67%|██████▋   | 205/306 [00:52<00:21,  4.76it/s]

 68%|██████▊   | 207/306 [00:53<00:16,  5.91it/s]

 68%|██████▊   | 209/306 [00:54<00:34,  2.79it/s]

 69%|██████▉   | 211/306 [00:54<00:25,  3.68it/s]

 70%|██████▉   | 213/306 [00:54<00:19,  4.73it/s]

 70%|███████   | 215/306 [00:55<00:15,  5.90it/s]

 71%|███████   | 217/306 [00:56<00:31,  2.83it/s]

 72%|███████▏  | 219/306 [00:56<00:23,  3.71it/s]

 72%|███████▏  | 221/306 [00:56<00:17,  4.75it/s]

 73%|███████▎  | 223/306 [00:57<00:14,  5.91it/s]

 74%|███████▎  | 225/306 [00:58<00:28,  2.82it/s]

 74%|███████▍  | 227/306 [00:58<00:21,  3.70it/s]

 75%|███████▍  | 229/306 [00:58<00:16,  4.73it/s]

 75%|███████▌  | 231/306 [00:59<00:12,  5.86it/s]

 76%|███████▌  | 233/306 [01:00<00:25,  2.89it/s]

 77%|███████▋  | 235/306 [01:00<00:18,  3.79it/s]

 77%|███████▋  | 237/306 [01:00<00:14,  4.86it/s]

 78%|███████▊  | 239/306 [01:00<00:11,  6.05it/s]

 79%|███████▉  | 241/306 [01:02<00:22,  2.86it/s]

 79%|███████▉  | 243/306 [01:02<00:16,  3.75it/s]

 80%|████████  | 245/306 [01:02<00:12,  4.81it/s]

 81%|████████  | 247/306 [01:02<00:09,  5.94it/s]

 81%|████████▏ | 249/306 [01:04<00:19,  2.86it/s]

 82%|████████▏ | 251/306 [01:04<00:14,  3.74it/s]

 83%|████████▎ | 253/306 [01:04<00:11,  4.78it/s]

 83%|████████▎ | 255/306 [01:04<00:08,  5.94it/s]

 84%|████████▍ | 257/306 [01:06<00:17,  2.78it/s]

 85%|████████▍ | 259/306 [01:06<00:12,  3.65it/s]

 85%|████████▌ | 261/306 [01:06<00:09,  4.70it/s]

 86%|████████▌ | 263/306 [01:07<00:07,  5.88it/s]

 87%|████████▋ | 265/306 [01:08<00:14,  2.84it/s]

 87%|████████▋ | 267/306 [01:08<00:10,  3.74it/s]

 88%|████████▊ | 269/306 [01:08<00:07,  4.80it/s]

 89%|████████▊ | 271/306 [01:08<00:05,  5.99it/s]

 89%|████████▉ | 273/306 [01:10<00:11,  2.79it/s]

 90%|████████▉ | 275/306 [01:10<00:08,  3.67it/s]

 91%|█████████ | 277/306 [01:10<00:06,  4.71it/s]

 91%|█████████ | 279/306 [01:11<00:04,  5.86it/s]

 92%|█████████▏| 281/306 [01:12<00:08,  2.88it/s]

 92%|█████████▏| 283/306 [01:12<00:06,  3.77it/s]

 93%|█████████▎| 285/306 [01:12<00:04,  4.83it/s]

 94%|█████████▍| 287/306 [01:12<00:03,  6.00it/s]

 94%|█████████▍| 289/306 [01:14<00:05,  2.87it/s]

 95%|█████████▌| 291/306 [01:14<00:03,  3.76it/s]

 96%|█████████▌| 293/306 [01:14<00:02,  4.81it/s]

 96%|█████████▋| 295/306 [01:14<00:01,  5.96it/s]

 97%|█████████▋| 297/306 [01:16<00:03,  2.83it/s]

 98%|█████████▊| 299/306 [01:16<00:01,  3.72it/s]

 98%|█████████▊| 301/306 [01:16<00:01,  4.77it/s]

 99%|█████████▉| 303/306 [01:16<00:00,  5.95it/s]

100%|█████████▉| 305/306 [01:17<00:00,  6.55it/s]

100%|██████████| 306/306 [01:17<00:00,  3.96it/s]

resnet Epoch 3 loss 1.6442 val_acc 0.7089

Saved best resnet to /kaggle/working/writer_resnet_best.pth

  0%|          | 0/306 [00:00<?, ?it/s]

  0%|          | 1/306 [00:02<15:12,  2.99s/it]

  1%|          | 3/306 [00:03<04:10,  1.21it/s]

  2%|▏         | 5/306 [00:03<02:11,  2.28it/s]

  2%|▏         | 7/306 [00:03<01:24,  3.53it/s]

  3%|▎         | 9/306 [00:04<02:19,  2.13it/s]

  4%|▎         | 11/306 [00:05<01:37,  3.03it/s]

  4%|▍         | 13/306 [00:05<01:11,  4.11it/s]

  5%|▍         | 15/306 [00:05<00:54,  5.34it/s]

  6%|▌         | 17/306 [00:06<01:49,  2.65it/s]

  6%|▌         | 19/306 [00:07<01:21,  3.53it/s]

  7%|▋         | 21/306 [00:07<01:02,  4.59it/s]

  8%|▊         | 23/306 [00:07<00:49,  5.75it/s]

  8%|▊         | 25/306 [00:08<01:41,  2.78it/s]

  9%|▉         | 27/306 [00:09<01:15,  3.67it/s]

  9%|▉         | 29/306 [00:09<00:58,  4.73it/s]

 10%|█         | 31/306 [00:09<00:46,  5.92it/s]

 11%|█         | 33/306 [00:11<01:37,  2.79it/s]

 11%|█▏        | 35/306 [00:11<01:13,  3.68it/s]

 12%|█▏        | 37/306 [00:11<00:57,  4.72it/s]

 13%|█▎        | 39/306 [00:11<00:45,  5.86it/s]

 13%|█▎        | 41/306 [00:12<01:33,  2.85it/s]

 14%|█▍        | 43/306 [00:13<01:10,  3.72it/s]

 15%|█▍        | 45/306 [00:13<00:54,  4.77it/s]

 15%|█▌        | 47/306 [00:13<00:43,  5.94it/s]

 16%|█▌        | 49/306 [00:15<01:31,  2.82it/s]

 17%|█▋        | 51/306 [00:15<01:08,  3.71it/s]

 17%|█▋        | 53/306 [00:15<00:53,  4.75it/s]

 18%|█▊        | 55/306 [00:15<00:42,  5.91it/s]

 19%|█▊        | 57/306 [00:17<01:29,  2.78it/s]

 19%|█▉        | 59/306 [00:17<01:07,  3.66it/s]

 20%|█▉        | 61/306 [00:17<00:52,  4.70it/s]

 21%|██        | 63/306 [00:17<00:41,  5.87it/s]

 21%|██        | 65/306 [00:19<01:27,  2.75it/s]

 22%|██▏       | 67/306 [00:19<01:05,  3.63it/s]

 23%|██▎       | 69/306 [00:19<00:50,  4.66it/s]

 23%|██▎       | 71/306 [00:19<00:40,  5.81it/s]

 24%|██▍       | 73/306 [00:21<01:24,  2.75it/s]

 25%|██▍       | 75/306 [00:21<01:03,  3.63it/s]

 25%|██▌       | 77/306 [00:21<00:49,  4.66it/s]

 26%|██▌       | 79/306 [00:21<00:38,  5.84it/s]

 26%|██▋       | 81/306 [00:23<01:27,  2.57it/s]

 27%|██▋       | 83/306 [00:23<01:05,  3.40it/s]

 28%|██▊       | 85/306 [00:23<00:50,  4.40it/s]

 28%|██▊       | 87/306 [00:23<00:39,  5.53it/s]

 29%|██▉       | 89/306 [00:25<01:22,  2.63it/s]

 30%|██▉       | 91/306 [00:25<01:01,  3.47it/s]

 30%|███       | 93/306 [00:25<00:47,  4.48it/s]

 31%|███       | 95/306 [00:25<00:37,  5.61it/s]

 32%|███▏      | 97/306 [00:27<01:20,  2.61it/s]

 32%|███▏      | 99/306 [00:27<01:00,  3.45it/s]

 33%|███▎      | 101/306 [00:27<00:46,  4.45it/s]

 34%|███▎      | 103/306 [00:28<00:36,  5.60it/s]

 34%|███▍      | 105/306 [00:29<01:17,  2.61it/s]

 35%|███▍      | 107/306 [00:29<00:57,  3.45it/s]

 36%|███▌      | 109/306 [00:30<00:44,  4.44it/s]

 36%|███▋      | 111/306 [00:30<00:35,  5.55it/s]

 37%|███▋      | 113/306 [00:32<01:28,  2.18it/s]

 38%|███▊      | 115/306 [00:32<01:05,  2.91it/s]

 38%|███▊      | 117/306 [00:32<00:49,  3.82it/s]

 39%|███▉      | 119/306 [00:32<00:38,  4.88it/s]

 40%|███▉      | 121/306 [00:35<01:28,  2.10it/s]

 40%|████      | 123/306 [00:35<01:05,  2.81it/s]

 41%|████      | 125/306 [00:35<00:49,  3.69it/s]

 42%|████▏     | 127/306 [00:35<00:37,  4.72it/s]

 42%|████▏     | 129/306 [00:37<01:19,  2.23it/s]

 43%|████▎     | 131/306 [00:37<00:58,  2.98it/s]

 43%|████▎     | 133/306 [00:37<00:44,  3.90it/s]

 44%|████▍     | 135/306 [00:38<00:34,  4.98it/s]

 45%|████▍     | 137/306 [00:40<01:25,  1.97it/s]

 45%|████▌     | 139/306 [00:40<01:03,  2.65it/s]

 46%|████▌     | 141/306 [00:40<00:47,  3.50it/s]

 47%|████▋     | 143/306 [00:40<00:36,  4.51it/s]

 47%|████▋     | 145/306 [00:43<01:27,  1.85it/s]

 48%|████▊     | 147/306 [00:43<01:03,  2.50it/s]

 49%|████▊     | 149/306 [00:43<00:47,  3.31it/s]

 49%|████▉     | 151/306 [00:43<00:36,  4.30it/s]

 50%|█████     | 153/306 [00:46<01:23,  1.84it/s]

 51%|█████     | 155/306 [00:46<01:00,  2.49it/s]

 51%|█████▏    | 157/306 [00:46<00:45,  3.31it/s]

 52%|█████▏    | 159/306 [00:46<00:34,  4.29it/s]

 53%|█████▎    | 161/306 [00:50<01:33,  1.54it/s]

 53%|█████▎    | 163/306 [00:50<01:07,  2.11it/s]

 54%|█████▍    | 165/306 [00:50<00:49,  2.83it/s]

 55%|█████▍    | 167/306 [00:50<00:37,  3.71it/s]

 55%|█████▌    | 169/306 [00:53<01:33,  1.47it/s]

 56%|█████▌    | 171/306 [00:53<01:07,  2.01it/s]

 57%|█████▋    | 173/306 [00:54<00:49,  2.71it/s]

 57%|█████▋    | 175/306 [00:54<00:36,  3.57it/s]

 58%|█████▊    | 177/306 [00:57<01:31,  1.41it/s]

 58%|█████▊    | 179/306 [00:57<01:05,  1.93it/s]

 59%|█████▉    | 181/306 [00:57<00:48,  2.59it/s]

 60%|█████▉    | 183/306 [00:58<00:35,  3.42it/s]

 60%|██████    | 185/306 [01:01<01:20,  1.50it/s]

 61%|██████    | 187/306 [01:01<00:58,  2.04it/s]

 62%|██████▏   | 189/306 [01:01<00:42,  2.74it/s]

 62%|██████▏   | 191/306 [01:01<00:31,  3.61it/s]

 63%|██████▎   | 193/306 [01:04<01:16,  1.48it/s]

 64%|██████▎   | 195/306 [01:04<00:54,  2.02it/s]

 64%|██████▍   | 197/306 [01:05<00:40,  2.72it/s]

 65%|██████▌   | 199/306 [01:05<00:29,  3.58it/s]

 66%|██████▌   | 201/306 [01:08<01:10,  1.49it/s]

 66%|██████▋   | 203/306 [01:08<00:50,  2.04it/s]

 67%|██████▋   | 205/306 [01:08<00:36,  2.74it/s]

 68%|██████▊   | 207/306 [01:08<00:27,  3.61it/s]

 68%|██████▊   | 209/306 [01:11<00:58,  1.65it/s]

 69%|██████▉   | 211/306 [01:11<00:42,  2.24it/s]

 70%|██████▉   | 213/306 [01:11<00:31,  2.99it/s]

 70%|███████   | 215/306 [01:12<00:23,  3.92it/s]

 71%|███████   | 217/306 [01:15<01:07,  1.31it/s]

 72%|███████▏  | 219/306 [01:16<00:48,  1.80it/s]

 72%|███████▏  | 221/306 [01:16<00:34,  2.44it/s]

 73%|███████▎  | 223/306 [01:16<00:25,  3.23it/s]

 74%|███████▎  | 225/306 [01:19<00:58,  1.38it/s]

 74%|███████▍  | 227/306 [01:19<00:41,  1.89it/s]

 75%|███████▍  | 229/306 [01:20<00:30,  2.55it/s]

 75%|███████▌  | 231/306 [01:20<00:22,  3.37it/s]

 76%|███████▌  | 233/306 [01:21<00:33,  2.20it/s]

 77%|███████▋  | 235/306 [01:21<00:24,  2.94it/s]

 77%|███████▋  | 237/306 [01:22<00:17,  3.85it/s]

 78%|███████▊  | 239/306 [01:22<00:13,  4.90it/s]

 79%|███████▉  | 241/306 [01:25<00:38,  1.68it/s]

 79%|███████▉  | 243/306 [01:25<00:27,  2.28it/s]

 80%|████████  | 245/306 [01:25<00:20,  3.04it/s]

 81%|████████  | 247/306 [01:25<00:14,  3.96it/s]

 81%|████████▏ | 249/306 [01:29<00:42,  1.35it/s]

 82%|████████▏ | 251/306 [01:29<00:29,  1.84it/s]

 83%|████████▎ | 253/306 [01:29<00:21,  2.49it/s]

 83%|████████▎ | 255/306 [01:29<00:15,  3.31it/s]

 84%|████████▍ | 257/306 [01:34<00:40,  1.22it/s]

 85%|████████▍ | 259/306 [01:34<00:28,  1.67it/s]

 85%|████████▌ | 261/306 [01:34<00:19,  2.27it/s]

 86%|████████▌ | 263/306 [01:34<00:14,  3.04it/s]

 87%|████████▋ | 265/306 [01:38<00:35,  1.16it/s]

 87%|████████▋ | 267/306 [01:38<00:24,  1.59it/s]

 88%|████████▊ | 269/306 [01:38<00:17,  2.16it/s]

 89%|████████▊ | 271/306 [01:39<00:12,  2.90it/s]

 89%|████████▉ | 273/306 [01:43<00:31,  1.05it/s]

 90%|████████▉ | 275/306 [01:44<00:21,  1.45it/s]

 91%|█████████ | 277/306 [01:44<00:14,  1.98it/s]

 91%|█████████ | 279/306 [01:44<00:10,  2.66it/s]

 92%|█████████▏| 281/306 [01:48<00:23,  1.08it/s]

 92%|█████████▏| 283/306 [01:48<00:15,  1.50it/s]

 93%|█████████▎| 285/306 [01:49<00:10,  2.04it/s]

 94%|█████████▍| 287/306 [01:49<00:06,  2.75it/s]

 94%|█████████▍| 289/306 [01:53<00:15,  1.12it/s]

 95%|█████████▌| 291/306 [01:53<00:09,  1.55it/s]

 96%|█████████▌| 293/306 [01:53<00:06,  2.11it/s]

 96%|█████████▋| 295/306 [01:53<00:03,  2.83it/s]

 97%|█████████▋| 297/306 [01:57<00:07,  1.17it/s]

 98%|█████████▊| 299/306 [01:58<00:04,  1.62it/s]

 98%|█████████▊| 301/306 [01:58<00:02,  2.20it/s]

 99%|█████████▉| 303/306 [01:58<00:01,  2.95it/s]

100%|█████████▉| 305/306 [01:59<00:00,  2.64it/s]

100%|██████████| 306/306 [01:59<00:00,  2.56it/s]

resnet Epoch 4 loss 1.5186 val_acc 0.7341
Saved best resnet to /kaggle/working/writer_resnet_best.pth

  0%|          | 0/306 [00:00<?, ?it/s]

  0%|          | 1/306 [00:05<28:29,  5.60s/it]

  1%|          | 3/306 [00:05<07:36,  1.51s/it]

  2%|▏         | 5/306 [00:05<03:51,  1.30it/s]

  2%|▏         | 7/306 [00:06<02:21,  2.11it/s]

  3%|▎         | 9/306 [00:11<06:37,  1.34s/it]

  4%|▎         | 11/306 [00:11<04:24,  1.12it/s]

  4%|▍         | 13/306 [00:11<03:01,  1.61it/s]

  5%|▍         | 15/306 [00:12<02:08,  2.26it/s]

  6%|▌         | 17/306 [00:15<04:22,  1.10it/s]

  6%|▌         | 19/306 [00:15<03:06,  1.54it/s]

  7%|▋         | 21/306 [00:16<02:14,  2.12it/s]

  8%|▊         | 23/306 [00:16<01:39,  2.86it/s]

  8%|▊         | 25/306 [00:19<03:42,  1.26it/s]

  9%|▉         | 27/306 [00:20<02:40,  1.74it/s]

  9%|▉         | 29/306 [00:20<01:57,  2.37it/s]

 10%|█         | 31/306 [00:20<01:27,  3.16it/s]

 11%|█         | 33/306 [00:23<03:28,  1.31it/s]

 11%|█▏        | 35/306 [00:24<02:30,  1.80it/s]

 12%|█▏        | 37/306 [00:24<01:50,  2.44it/s]

 13%|█▎        | 39/306 [00:24<01:22,  3.24it/s]

 13%|█▎        | 41/306 [00:27<03:12,  1.38it/s]

 14%|█▍        | 43/306 [00:27<02:19,  1.88it/s]

 15%|█▍        | 45/306 [00:28<01:42,  2.54it/s]

 15%|█▌        | 47/306 [00:28<01:16,  3.37it/s]

 16%|█▌        | 49/306 [00:31<02:57,  1.45it/s]

 17%|█▋        | 51/306 [00:31<02:08,  1.98it/s]

 17%|█▋        | 53/306 [00:31<01:34,  2.67it/s]

 18%|█▊        | 55/306 [00:31<01:11,  3.52it/s]

 19%|█▊        | 57/306 [00:33<01:49,  2.27it/s]

 19%|█▉        | 59/306 [00:33<01:21,  3.02it/s]

 20%|█▉        | 61/306 [00:33<01:02,  3.95it/s]

 21%|██        | 63/306 [00:33<00:48,  5.02it/s]

 21%|██        | 65/306 [00:35<01:30,  2.65it/s]

 22%|██▏       | 67/306 [00:35<01:08,  3.51it/s]

 23%|██▎       | 69/306 [00:35<00:52,  4.53it/s]

 23%|██▎       | 71/306 [00:35<00:41,  5.69it/s]

 24%|██▍       | 73/306 [00:37<01:35,  2.44it/s]

 25%|██▍       | 75/306 [00:37<01:11,  3.25it/s]

 25%|██▌       | 77/306 [00:38<00:54,  4.23it/s]

 26%|██▌       | 79/306 [00:38<00:42,  5.35it/s]

 26%|██▋       | 81/306 [00:39<01:21,  2.76it/s]

 27%|██▋       | 83/306 [00:39<01:01,  3.63it/s]

 28%|██▊       | 85/306 [00:40<00:47,  4.67it/s]

 28%|██▊       | 87/306 [00:40<00:37,  5.82it/s]

 29%|██▉       | 89/306 [00:41<01:20,  2.70it/s]

 30%|██▉       | 91/306 [00:42<01:00,  3.56it/s]

 30%|███       | 93/306 [00:42<00:46,  4.59it/s]

 31%|███       | 95/306 [00:42<00:36,  5.74it/s]

 32%|███▏      | 97/306 [00:44<01:31,  2.28it/s]

 32%|███▏      | 99/306 [00:44<01:08,  3.04it/s]

 33%|███▎      | 101/306 [00:44<00:51,  3.98it/s]

 34%|███▎      | 103/306 [00:44<00:40,  5.06it/s]

 34%|███▍      | 105/306 [00:46<01:29,  2.24it/s]

 35%|███▍      | 107/306 [00:47<01:06,  2.98it/s]

 36%|███▌      | 109/306 [00:47<00:50,  3.89it/s]

 36%|███▋      | 111/306 [00:47<00:39,  4.95it/s]

 37%|███▋      | 113/306 [00:49<01:21,  2.37it/s]

 38%|███▊      | 115/306 [00:49<01:00,  3.15it/s]

 38%|███▊      | 117/306 [00:49<00:46,  4.10it/s]

 39%|███▉      | 119/306 [00:49<00:35,  5.20it/s]

 40%|███▉      | 121/306 [00:51<01:16,  2.41it/s]

 40%|████      | 123/306 [00:51<00:57,  3.20it/s]

 41%|████      | 125/306 [00:51<00:43,  4.16it/s]

 42%|████▏     | 127/306 [00:51<00:34,  5.26it/s]

 42%|████▏     | 129/306 [00:54<01:41,  1.75it/s]

 43%|████▎     | 131/306 [00:55<01:13,  2.37it/s]

 43%|████▎     | 133/306 [00:55<00:54,  3.15it/s]

 44%|████▍     | 135/306 [00:55<00:41,  4.11it/s]

 45%|████▍     | 137/306 [00:57<01:28,  1.90it/s]

 45%|████▌     | 139/306 [00:57<01:05,  2.56it/s]

 46%|████▌     | 141/306 [00:57<00:48,  3.39it/s]

 47%|████▋     | 143/306 [00:58<00:37,  4.39it/s]

 47%|████▋     | 145/306 [01:00<01:18,  2.06it/s]

 48%|████▊     | 147/306 [01:00<00:57,  2.77it/s]

 49%|████▊     | 149/306 [01:00<00:43,  3.65it/s]

 49%|████▉     | 151/306 [01:00<00:33,  4.69it/s]

 50%|█████     | 153/306 [01:02<01:12,  2.11it/s]

 51%|█████     | 155/306 [01:03<00:53,  2.84it/s]

 51%|█████▏    | 157/306 [01:03<00:39,  3.73it/s]

 52%|█████▏    | 159/306 [01:03<00:30,  4.78it/s]

 53%|█████▎    | 161/306 [01:05<01:05,  2.23it/s]

 53%|█████▎    | 163/306 [01:05<00:48,  2.98it/s]

 54%|█████▍    | 165/306 [01:05<00:36,  3.88it/s]

 55%|█████▍    | 167/306 [01:05<00:28,  4.96it/s]

 55%|█████▌    | 169/306 [01:08<01:15,  1.83it/s]

 56%|█████▌    | 171/306 [01:08<00:54,  2.47it/s]

 57%|█████▋    | 173/306 [01:08<00:40,  3.28it/s]

 57%|█████▋    | 175/306 [01:08<00:30,  4.26it/s]

 58%|█████▊    | 177/306 [01:11<01:05,  1.95it/s]

 58%|█████▊    | 179/306 [01:11<00:48,  2.63it/s]

 59%|█████▉    | 181/306 [01:11<00:36,  3.47it/s]

 60%|█████▉    | 183/306 [01:11<00:27,  4.48it/s]

 60%|██████    | 185/306 [01:13<00:53,  2.25it/s]

 61%|██████    | 187/306 [01:13<00:39,  3.01it/s]

 62%|██████▏   | 189/306 [01:13<00:29,  3.93it/s]

 62%|██████▏   | 191/306 [01:14<00:22,  5.01it/s]

 63%|██████▎   | 193/306 [01:16<00:51,  2.21it/s]

 64%|██████▎   | 195/306 [01:16<00:37,  2.96it/s]

 64%|██████▍   | 197/306 [01:16<00:28,  3.88it/s]

 65%|██████▌   | 199/306 [01:16<00:21,  4.95it/s]

 66%|██████▌   | 201/306 [01:19<00:54,  1.94it/s]

 66%|██████▋   | 203/306 [01:19<00:39,  2.62it/s]

 67%|██████▋   | 205/306 [01:19<00:29,  3.46it/s]

 68%|██████▊   | 207/306 [01:19<00:22,  4.47it/s]

 68%|██████▊   | 209/306 [01:21<00:47,  2.03it/s]

 69%|██████▉   | 211/306 [01:21<00:34,  2.73it/s]

 70%|██████▉   | 213/306 [01:21<00:25,  3.60it/s]

 70%|███████   | 215/306 [01:22<00:19,  4.62it/s]

 71%|███████   | 217/306 [01:25<00:54,  1.65it/s]

 72%|███████▏  | 219/306 [01:25<00:38,  2.24it/s]

 72%|███████▏  | 221/306 [01:25<00:28,  2.99it/s]

 73%|███████▎  | 223/306 [01:25<00:21,  3.91it/s]

 74%|███████▎  | 225/306 [01:28<00:50,  1.60it/s]

 74%|███████▍  | 227/306 [01:28<00:36,  2.17it/s]

 75%|███████▍  | 229/306 [01:28<00:26,  2.91it/s]

 75%|███████▌  | 231/306 [01:28<00:19,  3.82it/s]

 76%|███████▌  | 233/306 [01:30<00:34,  2.14it/s]

 77%|███████▋  | 235/306 [01:31<00:24,  2.86it/s]

 77%|███████▋  | 237/306 [01:31<00:18,  3.76it/s]

 78%|███████▊  | 239/306 [01:31<00:13,  4.81it/s]

 79%|███████▉  | 241/306 [01:32<00:25,  2.53it/s]

 79%|███████▉  | 243/306 [01:33<00:18,  3.35it/s]

 80%|████████  | 245/306 [01:33<00:14,  4.34it/s]

 81%|████████  | 247/306 [01:33<00:10,  5.47it/s]

 81%|████████▏ | 249/306 [01:35<00:28,  2.03it/s]

 82%|████████▏ | 251/306 [01:35<00:20,  2.73it/s]

 83%|████████▎ | 253/306 [01:36<00:14,  3.60it/s]

 83%|████████▎ | 255/306 [01:36<00:11,  4.63it/s]

 84%|████████▍ | 257/306 [01:38<00:27,  1.80it/s]

 85%|████████▍ | 259/306 [01:39<00:19,  2.43it/s]

 85%|████████▌ | 261/306 [01:39<00:13,  3.23it/s]

 86%|████████▌ | 263/306 [01:39<00:10,  4.18it/s]

 87%|████████▋ | 265/306 [01:41<00:20,  2.00it/s]

 87%|████████▋ | 267/306 [01:41<00:14,  2.69it/s]

 88%|████████▊ | 269/306 [01:41<00:10,  3.56it/s]

 89%|████████▊ | 271/306 [01:42<00:07,  4.58it/s]

 89%|████████▉ | 273/306 [01:43<00:13,  2.43it/s]

 90%|████████▉ | 275/306 [01:43<00:09,  3.22it/s]

 91%|█████████ | 277/306 [01:44<00:06,  4.19it/s]

 91%|█████████ | 279/306 [01:44<00:05,  5.31it/s]

 92%|█████████▏| 281/306 [01:45<00:09,  2.63it/s]

 92%|█████████▏| 283/306 [01:46<00:06,  3.48it/s]

 93%|█████████▎| 285/306 [01:46<00:04,  4.47it/s]

 94%|█████████▍| 287/306 [01:46<00:03,  5.62it/s]

 94%|█████████▍| 289/306 [01:47<00:06,  2.68it/s]

 95%|█████████▌| 291/306 [01:48<00:04,  3.54it/s]

 96%|█████████▌| 293/306 [01:48<00:02,  4.56it/s]

 96%|█████████▋| 295/306 [01:48<00:01,  5.70it/s]

 97%|█████████▋| 297/306 [01:50<00:03,  2.68it/s]

 98%|█████████▊| 299/306 [01:50<00:01,  3.54it/s]

 98%|█████████▊| 301/306 [01:50<00:01,  4.56it/s]

 99%|█████████▉| 303/306 [01:50<00:00,  5.70it/s]

100%|█████████▉| 305/306 [01:50<00:00,  6.21it/s]

100%|██████████| 306/306 [01:50<00:00,  2.76it/s]

resnet Epoch 5 loss 1.4604 val_acc 0.7436
Saved best resnet to /kaggle/working/writer_resnet_best.pth
Best resnet val_acc: 0.7436

Training convnext

Downloading: "https://download.pytorch.org/models/convnext_tiny-983f1562.pth" to /root/.cache/torch/hub/checkpoints/convnext_tiny-983f1562.pth

  0%|          | 0.00/109M [00:00<?, ?B/s]

  7%|▋         | 8.12M/109M [00:00<00:01, 85.1MB/s]

 31%|███       | 33.6M/109M [00:00<00:00, 192MB/s]

 54%|█████▍    | 59.2M/109M [00:00<00:00, 227MB/s]

 78%|███████▊  | 84.9M/109M [00:00<00:00, 243MB/s]

100%|██████████| 109M/109M [00:00<00:00, 231MB/s]

Loaded pretrained convnext from /kaggle/input/datasets/cbdsigmas/tranfer-to-writer-model/convnext_best.pth
Missing keys: ['classifier.2.1.weight', 'classifier.2.1.bias']
Unexpected keys: []

  0%|          | 0/306 [00:00<?, ?it/s]

  0%|          | 1/306 [00:32<2:45:50, 32.63s/it]

  1%|          | 2/306 [00:54<2:14:38, 26.58s/it]

  1%|          | 3/306 [00:55<1:13:29, 14.55s/it]

  1%|▏         | 4/306 [00:55<44:49,  8.91s/it]

  2%|▏         | 5/306 [00:55<29:01,  5.78s/it]

  2%|▏         | 6/306 [00:55<19:30,  3.90s/it]

  2%|▏         | 7/306 [00:56<13:29,  2.71s/it]

  3%|▎         | 8/306 [00:56<09:36,  1.93s/it]

  3%|▎         | 9/306 [00:56<06:57,  1.41s/it]

  3%|▎         | 10/306 [00:56<05:10,  1.05s/it]

  4%|▎         | 11/306 [00:57<03:57,  1.24it/s]

  4%|▍         | 12/306 [00:57<03:06,  1.57it/s]

  4%|▍         | 13/306 [00:57<02:31,  1.93it/s]

  5%|▍         | 14/306 [00:57<02:07,  2.29it/s]

  5%|▍         | 15/306 [00:58<01:50,  2.63it/s]

  5%|▌         | 16/306 [00:58<01:41,  2.86it/s]

  6%|▌         | 17/306 [00:58<01:32,  3.12it/s]

  6%|▌         | 18/306 [00:59<01:26,  3.34it/s]

  6%|▌         | 19/306 [00:59<01:21,  3.50it/s]

  7%|▋         | 20/306 [00:59<01:18,  3.62it/s]

  7%|▋         | 21/306 [00:59<01:16,  3.71it/s]

  7%|▋         | 22/306 [01:00<01:15,  3.77it/s]

  8%|▊         | 23/306 [01:00<01:13,  3.84it/s]

  8%|▊         | 24/306 [01:00<01:15,  3.76it/s]

  8%|▊         | 25/306 [01:00<01:14,  3.79it/s]

  8%|▊         | 26/306 [01:01<01:13,  3.83it/s]

  9%|▉         | 27/306 [01:01<01:12,  3.87it/s]

  9%|▉         | 28/306 [01:01<01:11,  3.89it/s]

  9%|▉         | 29/306 [01:01<01:10,  3.91it/s]

 10%|▉         | 30/306 [01:02<01:10,  3.94it/s]

 10%|█         | 31/306 [01:02<01:09,  3.96it/s]

 10%|█         | 32/306 [01:02<01:10,  3.87it/s]

 11%|█         | 33/306 [01:02<01:09,  3.95it/s]

 11%|█         | 34/306 [01:03<01:07,  4.00it/s]

 11%|█▏        | 35/306 [01:03<01:08,  3.98it/s]

 12%|█▏        | 36/306 [01:03<01:08,  3.95it/s]

 12%|█▏        | 37/306 [01:03<01:07,  4.00it/s]

 12%|█▏        | 38/306 [01:04<01:06,  4.05it/s]

 13%|█▎        | 39/306 [01:04<01:06,  4.04it/s]

 13%|█▎        | 40/306 [01:04<01:07,  3.96it/s]

 13%|█▎        | 41/306 [01:04<01:06,  4.00it/s]

 14%|█▎        | 42/306 [01:05<01:05,  4.01it/s]

 14%|█▍        | 43/306 [01:05<01:06,  3.96it/s]

 14%|█▍        | 44/306 [01:05<01:06,  3.95it/s]

 15%|█▍        | 45/306 [01:05<01:05,  4.00it/s]

 15%|█▌        | 46/306 [01:06<01:04,  4.02it/s]

 15%|█▌        | 47/306 [01:06<01:04,  4.04it/s]

 16%|█▌        | 48/306 [01:06<01:05,  3.93it/s]

 16%|█▌        | 49/306 [01:06<01:04,  3.98it/s]

 16%|█▋        | 50/306 [01:07<01:03,  4.01it/s]

 17%|█▋        | 51/306 [01:07<01:04,  3.98it/s]

 17%|█▋        | 52/306 [01:07<01:03,  3.98it/s]

 17%|█▋        | 53/306 [01:07<01:03,  4.02it/s]

 18%|█▊        | 54/306 [01:08<01:02,  4.04it/s]

 18%|█▊        | 55/306 [01:08<01:02,  4.04it/s]

 18%|█▊        | 56/306 [01:08<01:03,  3.96it/s]

 19%|█▊        | 57/306 [01:08<01:02,  4.00it/s]

 19%|█▉        | 58/306 [01:09<01:01,  4.05it/s]

 19%|█▉        | 59/306 [01:09<01:01,  4.05it/s]

 20%|█▉        | 60/306 [01:09<01:00,  4.07it/s]

 20%|█▉        | 61/306 [01:09<00:59,  4.08it/s]

 20%|██        | 62/306 [01:10<00:59,  4.08it/s]

 21%|██        | 63/306 [01:10<00:59,  4.08it/s]

 21%|██        | 64/306 [01:10<01:00,  3.98it/s]

 21%|██        | 65/306 [01:10<01:00,  4.02it/s]

 22%|██▏       | 66/306 [01:11<00:59,  4.00it/s]

 22%|██▏       | 67/306 [01:11<00:59,  3.99it/s]

 22%|██▏       | 68/306 [01:11<00:59,  4.01it/s]

 23%|██▎       | 69/306 [01:11<00:58,  4.03it/s]

 23%|██▎       | 70/306 [01:12<00:58,  4.05it/s]

 23%|██▎       | 71/306 [01:12<00:57,  4.06it/s]

 24%|██▎       | 72/306 [01:12<00:59,  3.93it/s]

 24%|██▍       | 73/306 [01:12<00:58,  3.97it/s]

 24%|██▍       | 74/306 [01:13<00:58,  4.00it/s]

 25%|██▍       | 75/306 [01:13<00:57,  3.99it/s]

 25%|██▍       | 76/306 [01:13<00:58,  3.92it/s]

 25%|██▌       | 77/306 [01:13<00:58,  3.93it/s]

 25%|██▌       | 78/306 [01:14<00:57,  3.97it/s]

 26%|██▌       | 79/306 [01:14<00:57,  3.97it/s]

 26%|██▌       | 80/306 [01:14<00:57,  3.92it/s]

 26%|██▋       | 81/306 [01:14<00:56,  3.95it/s]

 27%|██▋       | 82/306 [01:15<00:56,  3.98it/s]

 27%|██▋       | 83/306 [01:15<00:55,  4.00it/s]

 27%|██▋       | 84/306 [01:15<00:55,  4.01it/s]

 28%|██▊       | 85/306 [01:15<00:55,  4.02it/s]

 28%|██▊       | 86/306 [01:16<00:54,  4.03it/s]

 28%|██▊       | 87/306 [01:16<00:54,  4.03it/s]

 29%|██▉       | 88/306 [01:16<00:54,  4.00it/s]

 29%|██▉       | 89/306 [01:16<00:54,  3.97it/s]

 29%|██▉       | 90/306 [01:17<00:54,  3.95it/s]

 30%|██▉       | 91/306 [01:17<00:55,  3.89it/s]

 30%|███       | 92/306 [01:17<00:54,  3.90it/s]

 30%|███       | 93/306 [01:17<00:54,  3.91it/s]

 31%|███       | 94/306 [01:18<00:54,  3.92it/s]

 31%|███       | 95/306 [01:18<00:53,  3.93it/s]

 31%|███▏      | 96/306 [01:18<00:53,  3.92it/s]

 32%|███▏      | 97/306 [01:18<00:53,  3.93it/s]

 32%|███▏      | 98/306 [01:19<00:52,  3.93it/s]

 32%|███▏      | 99/306 [01:19<00:52,  3.93it/s]

 33%|███▎      | 100/306 [01:19<00:52,  3.93it/s]

 33%|███▎      | 101/306 [01:19<00:52,  3.87it/s]

 33%|███▎      | 102/306 [01:20<00:52,  3.88it/s]

 34%|███▎      | 103/306 [01:20<00:52,  3.90it/s]

 34%|███▍      | 104/306 [01:20<00:51,  3.92it/s]

 34%|███▍      | 105/306 [01:20<00:50,  3.97it/s]

 35%|███▍      | 106/306 [01:21<00:49,  4.01it/s]

 35%|███▍      | 107/306 [01:21<00:49,  4.05it/s]

 35%|███▌      | 108/306 [01:21<00:48,  4.08it/s]

 36%|███▌      | 109/306 [01:21<00:48,  4.10it/s]

 36%|███▌      | 110/306 [01:22<00:47,  4.12it/s]

 36%|███▋      | 111/306 [01:22<00:50,  3.87it/s]

 37%|███▋      | 112/306 [01:22<00:49,  3.88it/s]

 37%|███▋      | 113/306 [01:22<00:49,  3.87it/s]

 37%|███▋      | 114/306 [01:23<00:48,  3.93it/s]

 38%|███▊      | 115/306 [01:23<00:47,  3.99it/s]

 38%|███▊      | 116/306 [01:23<00:47,  3.96it/s]

 38%|███▊      | 117/306 [01:23<00:48,  3.93it/s]

 39%|███▊      | 118/306 [01:24<00:48,  3.91it/s]

 39%|███▉      | 119/306 [01:24<00:47,  3.94it/s]

 39%|███▉      | 120/306 [01:24<00:46,  3.98it/s]

 40%|███▉      | 121/306 [01:25<00:58,  3.17it/s]

 40%|███▉      | 122/306 [01:25<00:54,  3.38it/s]

 40%|████      | 123/306 [01:25<00:51,  3.53it/s]

 41%|████      | 124/306 [01:25<00:49,  3.68it/s]

 41%|████      | 125/306 [01:26<00:47,  3.79it/s]

 41%|████      | 126/306 [01:26<00:46,  3.85it/s]

 42%|████▏     | 127/306 [01:26<00:45,  3.91it/s]

 42%|████▏     | 128/306 [01:26<00:44,  3.96it/s]

 42%|████▏     | 129/306 [01:27<01:21,  2.18it/s]

 42%|████▏     | 130/306 [01:28<01:10,  2.51it/s]

 43%|████▎     | 131/306 [01:28<01:02,  2.81it/s]

 43%|████▎     | 132/306 [01:28<00:56,  3.07it/s]

 43%|████▎     | 133/306 [01:28<00:52,  3.31it/s]

 44%|████▍     | 134/306 [01:29<00:49,  3.48it/s]

 44%|████▍     | 135/306 [01:29<00:47,  3.64it/s]

 44%|████▍     | 136/306 [01:29<00:45,  3.76it/s]

 45%|████▍     | 137/306 [01:30<01:20,  2.10it/s]

 45%|████▌     | 138/306 [01:30<01:08,  2.46it/s]

 45%|████▌     | 139/306 [01:31<00:59,  2.79it/s]

 46%|████▌     | 140/306 [01:31<00:54,  3.06it/s]

 46%|████▌     | 141/306 [01:31<00:50,  3.28it/s]

 46%|████▋     | 142/306 [01:31<00:47,  3.48it/s]

 47%|████▋     | 143/306 [01:32<00:44,  3.63it/s]

 47%|████▋     | 144/306 [01:32<00:43,  3.73it/s]

 47%|████▋     | 145/306 [01:33<01:23,  1.94it/s]

 48%|████▊     | 146/306 [01:33<01:10,  2.27it/s]

 48%|████▊     | 147/306 [01:33<01:01,  2.59it/s]

 48%|████▊     | 148/306 [01:34<00:55,  2.87it/s]

 49%|████▊     | 149/306 [01:34<00:50,  3.14it/s]

 49%|████▉     | 150/306 [01:34<00:46,  3.36it/s]

 49%|████▉     | 151/306 [01:34<00:43,  3.54it/s]

 50%|████▉     | 152/306 [01:35<00:41,  3.69it/s]

 50%|█████     | 153/306 [01:36<01:21,  1.87it/s]

 50%|█████     | 154/306 [01:36<01:08,  2.23it/s]

 51%|█████     | 155/306 [01:36<00:58,  2.56it/s]

 51%|█████     | 156/306 [01:37<00:52,  2.87it/s]

 51%|█████▏    | 157/306 [01:37<00:47,  3.13it/s]

 52%|█████▏    | 158/306 [01:37<00:44,  3.35it/s]

 52%|█████▏    | 159/306 [01:37<00:41,  3.53it/s]

 52%|█████▏    | 160/306 [01:38<00:39,  3.67it/s]

 53%|█████▎    | 161/306 [01:39<01:24,  1.73it/s]

 53%|█████▎    | 162/306 [01:39<01:09,  2.07it/s]

 53%|█████▎    | 163/306 [01:39<00:59,  2.41it/s]

 54%|█████▎    | 164/306 [01:40<00:52,  2.72it/s]

 54%|█████▍    | 165/306 [01:40<00:46,  3.01it/s]

 54%|█████▍    | 166/306 [01:40<00:42,  3.26it/s]

 55%|█████▍    | 167/306 [01:40<00:40,  3.47it/s]

 55%|█████▍    | 168/306 [01:41<00:38,  3.63it/s]

 55%|█████▌    | 169/306 [01:42<01:33,  1.47it/s]

 56%|█████▌    | 170/306 [01:42<01:15,  1.81it/s]

 56%|█████▌    | 171/306 [01:43<01:02,  2.16it/s]

 56%|█████▌    | 172/306 [01:43<00:53,  2.51it/s]

 57%|█████▋    | 173/306 [01:43<00:47,  2.83it/s]

 57%|█████▋    | 174/306 [01:43<00:42,  3.11it/s]

 57%|█████▋    | 175/306 [01:44<00:39,  3.34it/s]

 58%|█████▊    | 176/306 [01:44<00:36,  3.51it/s]

 58%|█████▊    | 177/306 [01:46<01:25,  1.50it/s]

 58%|█████▊    | 178/306 [01:46<01:09,  1.85it/s]

 58%|█████▊    | 179/306 [01:46<00:57,  2.21it/s]

 59%|█████▉    | 180/306 [01:46<00:49,  2.56it/s]

 59%|█████▉    | 181/306 [01:47<00:43,  2.88it/s]

 59%|█████▉    | 182/306 [01:47<00:39,  3.14it/s]

 60%|█████▉    | 183/306 [01:47<00:36,  3.36it/s]

 60%|██████    | 184/306 [01:47<00:34,  3.55it/s]

 60%|██████    | 185/306 [01:49<01:08,  1.76it/s]

 61%|██████    | 186/306 [01:49<00:57,  2.09it/s]

 61%|██████    | 187/306 [01:49<00:48,  2.43it/s]

 61%|██████▏   | 188/306 [01:49<00:42,  2.75it/s]

 62%|██████▏   | 189/306 [01:50<00:38,  3.05it/s]

 62%|██████▏   | 190/306 [01:50<00:35,  3.28it/s]

 62%|██████▏   | 191/306 [01:50<00:33,  3.48it/s]

 63%|██████▎   | 192/306 [01:50<00:31,  3.64it/s]

 63%|██████▎   | 193/306 [01:52<01:06,  1.71it/s]

 63%|██████▎   | 194/306 [01:52<00:54,  2.07it/s]

 64%|██████▎   | 195/306 [01:52<00:45,  2.43it/s]

 64%|██████▍   | 196/306 [01:52<00:39,  2.76it/s]

 64%|██████▍   | 197/306 [01:53<00:35,  3.05it/s]

 65%|██████▍   | 198/306 [01:53<00:33,  3.27it/s]

 65%|██████▌   | 199/306 [01:53<00:31,  3.44it/s]

 65%|██████▌   | 200/306 [01:53<00:29,  3.59it/s]

 66%|██████▌   | 201/306 [01:54<00:53,  1.95it/s]

 66%|██████▌   | 202/306 [01:55<00:45,  2.29it/s]

 66%|██████▋   | 203/306 [01:55<00:39,  2.62it/s]

 67%|██████▋   | 204/306 [01:55<00:34,  2.93it/s]

 67%|██████▋   | 205/306 [01:55<00:31,  3.20it/s]

 67%|██████▋   | 206/306 [01:56<00:29,  3.40it/s]

 68%|██████▊   | 207/306 [01:56<00:27,  3.57it/s]

 68%|██████▊   | 208/306 [01:56<00:26,  3.67it/s]

 68%|██████▊   | 209/306 [01:57<00:49,  1.96it/s]

 69%|██████▊   | 210/306 [01:57<00:41,  2.32it/s]

 69%|██████▉   | 211/306 [01:58<00:35,  2.65it/s]

 69%|██████▉   | 212/306 [01:58<00:31,  2.96it/s]

 70%|██████▉   | 213/306 [01:58<00:28,  3.23it/s]

 70%|██████▉   | 214/306 [01:58<00:26,  3.43it/s]

 70%|███████   | 215/306 [01:59<00:25,  3.60it/s]

 71%|███████   | 216/306 [01:59<00:24,  3.72it/s]

 71%|███████   | 217/306 [02:00<00:41,  2.16it/s]

 71%|███████   | 218/306 [02:00<00:35,  2.51it/s]

 72%|███████▏  | 219/306 [02:00<00:30,  2.82it/s]

 72%|███████▏  | 220/306 [02:01<00:27,  3.09it/s]

 72%|███████▏  | 221/306 [02:01<00:25,  3.31it/s]

 73%|███████▎  | 222/306 [02:01<00:24,  3.49it/s]

 73%|███████▎  | 223/306 [02:01<00:22,  3.62it/s]

 73%|███████▎  | 224/306 [02:02<00:22,  3.72it/s]

 74%|███████▎  | 225/306 [02:02<00:36,  2.23it/s]

 74%|███████▍  | 226/306 [02:03<00:31,  2.55it/s]

 74%|███████▍  | 227/306 [02:03<00:27,  2.86it/s]

 75%|███████▍  | 228/306 [02:03<00:24,  3.14it/s]

 75%|███████▍  | 229/306 [02:03<00:22,  3.36it/s]

 75%|███████▌  | 230/306 [02:04<00:21,  3.54it/s]

 75%|███████▌  | 231/306 [02:04<00:20,  3.68it/s]

 76%|███████▌  | 232/306 [02:04<00:19,  3.75it/s]

 76%|███████▌  | 233/306 [02:05<00:25,  2.90it/s]

 76%|███████▋  | 234/306 [02:05<00:22,  3.16it/s]

 77%|███████▋  | 235/306 [02:05<00:21,  3.37it/s]

 77%|███████▋  | 236/306 [02:06<00:19,  3.53it/s]

 77%|███████▋  | 237/306 [02:06<00:18,  3.65it/s]

 78%|███████▊  | 238/306 [02:06<00:18,  3.75it/s]

 78%|███████▊  | 239/306 [02:06<00:17,  3.82it/s]

 78%|███████▊  | 240/306 [02:07<00:17,  3.86it/s]

 79%|███████▉  | 241/306 [02:07<00:22,  2.91it/s]

 79%|███████▉  | 242/306 [02:07<00:20,  3.16it/s]

 79%|███████▉  | 243/306 [02:08<00:18,  3.38it/s]

 80%|███████▉  | 244/306 [02:08<00:17,  3.53it/s]

 80%|████████  | 245/306 [02:08<00:16,  3.64it/s]

 80%|████████  | 246/306 [02:08<00:16,  3.73it/s]

 81%|████████  | 247/306 [02:09<00:15,  3.81it/s]

 81%|████████  | 248/306 [02:09<00:14,  3.87it/s]

 81%|████████▏ | 249/306 [02:09<00:17,  3.19it/s]

 82%|████████▏ | 250/306 [02:10<00:16,  3.40it/s]

 82%|████████▏ | 251/306 [02:10<00:15,  3.57it/s]

 82%|████████▏ | 252/306 [02:10<00:14,  3.70it/s]

 83%|████████▎ | 253/306 [02:10<00:14,  3.77it/s]

 83%|████████▎ | 254/306 [02:11<00:13,  3.85it/s]

 83%|████████▎ | 255/306 [02:11<00:13,  3.90it/s]

 84%|████████▎ | 256/306 [02:11<00:12,  3.90it/s]

 84%|████████▍ | 257/306 [02:12<00:20,  2.45it/s]

 84%|████████▍ | 258/306 [02:12<00:17,  2.77it/s]

 85%|████████▍ | 259/306 [02:12<00:15,  3.05it/s]

 85%|████████▍ | 260/306 [02:13<00:13,  3.29it/s]

 85%|████████▌ | 261/306 [02:13<00:12,  3.47it/s]

 86%|████████▌ | 262/306 [02:13<00:12,  3.60it/s]

 86%|████████▌ | 263/306 [02:13<00:11,  3.68it/s]

 86%|████████▋ | 264/306 [02:14<00:11,  3.69it/s]

 87%|████████▋ | 265/306 [02:15<00:20,  2.04it/s]

 87%|████████▋ | 266/306 [02:15<00:16,  2.40it/s]

 87%|████████▋ | 267/306 [02:15<00:14,  2.72it/s]

 88%|████████▊ | 268/306 [02:15<00:12,  3.01it/s]

 88%|████████▊ | 269/306 [02:16<00:11,  3.25it/s]

 88%|████████▊ | 270/306 [02:16<00:10,  3.45it/s]

 89%|████████▊ | 271/306 [02:16<00:09,  3.59it/s]

 89%|████████▉ | 272/306 [02:16<00:09,  3.71it/s]

 89%|████████▉ | 273/306 [02:17<00:09,  3.37it/s]

 90%|████████▉ | 274/306 [02:17<00:09,  3.54it/s]

 90%|████████▉ | 275/306 [02:17<00:08,  3.66it/s]

 90%|█████████ | 276/306 [02:17<00:07,  3.76it/s]

 91%|█████████ | 277/306 [02:18<00:07,  3.84it/s]

 91%|█████████ | 278/306 [02:18<00:07,  3.89it/s]

 91%|█████████ | 279/306 [02:18<00:06,  3.90it/s]

 92%|█████████▏| 280/306 [02:18<00:06,  3.92it/s]

 92%|█████████▏| 281/306 [02:19<00:07,  3.28it/s]

 92%|█████████▏| 282/306 [02:19<00:06,  3.43it/s]

 92%|█████████▏| 283/306 [02:19<00:06,  3.56it/s]

 93%|█████████▎| 284/306 [02:20<00:05,  3.68it/s]

 93%|█████████▎| 285/306 [02:20<00:05,  3.76it/s]

 93%|█████████▎| 286/306 [02:20<00:05,  3.83it/s]

 94%|█████████▍| 287/306 [02:20<00:04,  3.88it/s]

 94%|█████████▍| 288/306 [02:21<00:04,  3.92it/s]

 94%|█████████▍| 289/306 [02:21<00:04,  3.74it/s]

 95%|█████████▍| 290/306 [02:21<00:04,  3.82it/s]

 95%|█████████▌| 291/306 [02:21<00:03,  3.87it/s]

 95%|█████████▌| 292/306 [02:22<00:03,  3.92it/s]

 96%|█████████▌| 293/306 [02:22<00:03,  3.94it/s]

 96%|█████████▌| 294/306 [02:22<00:03,  3.97it/s]

 96%|█████████▋| 295/306 [02:22<00:02,  3.98it/s]

 97%|█████████▋| 296/306 [02:23<00:02,  3.93it/s]

 97%|█████████▋| 297/306 [02:23<00:02,  3.79it/s]

 97%|█████████▋| 298/306 [02:23<00:02,  3.83it/s]

 98%|█████████▊| 299/306 [02:23<00:01,  3.82it/s]

 98%|█████████▊| 300/306 [02:24<00:01,  3.87it/s]

 98%|█████████▊| 301/306 [02:24<00:01,  3.91it/s]

 99%|█████████▊| 302/306 [02:24<00:01,  3.94it/s]

 99%|█████████▉| 303/306 [02:24<00:00,  3.97it/s]

 99%|█████████▉| 304/306 [02:25<00:00,  3.98it/s]

100%|█████████▉| 305/306 [02:25<00:00,  3.94it/s]

100%|██████████| 306/306 [02:25<00:00,  3.93it/s]

100%|██████████| 306/306 [02:25<00:00,  2.10it/s]

convnext Epoch 0 loss 2.7921 val_acc 0.5427

Saved best convnext to /kaggle/working/writer_convnext_best.pth

  0%|          | 0/306 [00:00<?, ?it/s]

  0%|          | 1/306 [00:03<16:37,  3.27s/it]

  1%|          | 2/306 [00:03<07:34,  1.50s/it]

  1%|          | 3/306 [00:03<04:40,  1.08it/s]

  1%|▏         | 4/306 [00:04<03:19,  1.51it/s]

  2%|▏         | 5/306 [00:04<02:34,  1.94it/s]

  2%|▏         | 6/306 [00:04<02:07,  2.35it/s]

  2%|▏         | 7/306 [00:04<01:50,  2.70it/s]

  3%|▎         | 8/306 [00:05<01:40,  2.96it/s]

  3%|▎         | 9/306 [00:05<01:32,  3.22it/s]

  3%|▎         | 10/306 [00:05<01:26,  3.41it/s]

  4%|▎         | 11/306 [00:05<01:22,  3.58it/s]

  4%|▍         | 12/306 [00:06<01:19,  3.69it/s]

  4%|▍         | 13/306 [00:06<01:17,  3.79it/s]

  5%|▍         | 14/306 [00:06<01:15,  3.85it/s]

  5%|▍         | 15/306 [00:06<01:14,  3.89it/s]

  5%|▌         | 16/306 [00:07<01:15,  3.84it/s]

  6%|▌         | 17/306 [00:07<01:14,  3.89it/s]

  6%|▌         | 18/306 [00:07<01:13,  3.93it/s]

  6%|▌         | 19/306 [00:07<01:12,  3.97it/s]

  7%|▋         | 20/306 [00:08<01:12,  3.96it/s]

  7%|▋         | 21/306 [00:08<01:11,  3.99it/s]

  7%|▋         | 22/306 [00:08<01:10,  4.00it/s]

  8%|▊         | 23/306 [00:08<01:10,  4.02it/s]

  8%|▊         | 24/306 [00:09<01:11,  3.96it/s]

  8%|▊         | 25/306 [00:09<01:10,  3.98it/s]

  8%|▊         | 26/306 [00:09<01:10,  4.00it/s]

  9%|▉         | 27/306 [00:09<01:09,  4.01it/s]

  9%|▉         | 28/306 [00:10<01:10,  3.96it/s]

  9%|▉         | 29/306 [00:10<01:10,  3.93it/s]

 10%|▉         | 30/306 [00:10<01:10,  3.89it/s]

 10%|█         | 31/306 [00:10<01:11,  3.87it/s]

 10%|█         | 32/306 [00:11<01:11,  3.85it/s]

 11%|█         | 33/306 [00:11<01:10,  3.88it/s]

 11%|█         | 34/306 [00:11<01:09,  3.91it/s]

 11%|█▏        | 35/306 [00:11<01:08,  3.93it/s]

 12%|█▏        | 36/306 [00:12<01:09,  3.91it/s]

 12%|█▏        | 37/306 [00:12<01:09,  3.88it/s]

 12%|█▏        | 38/306 [00:12<01:09,  3.87it/s]

 13%|█▎        | 39/306 [00:12<01:09,  3.82it/s]

 13%|█▎        | 40/306 [00:13<01:08,  3.86it/s]

 13%|█▎        | 41/306 [00:13<01:08,  3.89it/s]

 14%|█▎        | 42/306 [00:13<01:07,  3.93it/s]

 14%|█▍        | 43/306 [00:13<01:06,  3.95it/s]

 14%|█▍        | 44/306 [00:14<01:06,  3.97it/s]

 15%|█▍        | 45/306 [00:14<01:05,  3.97it/s]

 15%|█▌        | 46/306 [00:14<01:05,  3.98it/s]

 15%|█▌        | 47/306 [00:14<01:06,  3.91it/s]

 16%|█▌        | 48/306 [00:15<01:06,  3.90it/s]

 16%|█▌        | 49/306 [00:15<01:05,  3.91it/s]

 16%|█▋        | 50/306 [00:15<01:06,  3.88it/s]

 17%|█▋        | 51/306 [00:15<01:05,  3.88it/s]

 17%|█▋        | 52/306 [00:16<01:05,  3.90it/s]

 17%|█▋        | 53/306 [00:16<01:05,  3.88it/s]

 18%|█▊        | 54/306 [00:16<01:05,  3.87it/s]

 18%|█▊        | 55/306 [00:17<01:05,  3.81it/s]

 18%|█▊        | 56/306 [00:17<01:04,  3.85it/s]

 19%|█▊        | 57/306 [00:17<01:04,  3.89it/s]

 19%|█▉        | 58/306 [00:17<01:03,  3.91it/s]

 19%|█▉        | 59/306 [00:18<01:02,  3.94it/s]

 20%|█▉        | 60/306 [00:18<01:02,  3.93it/s]

 20%|█▉        | 61/306 [00:18<01:02,  3.95it/s]

 20%|██        | 62/306 [00:18<01:02,  3.90it/s]

 21%|██        | 63/306 [00:19<01:02,  3.89it/s]

 21%|██        | 64/306 [00:19<01:02,  3.89it/s]

 21%|██        | 65/306 [00:19<01:01,  3.92it/s]

 22%|██▏       | 66/306 [00:19<01:00,  3.94it/s]

 22%|██▏       | 67/306 [00:20<01:00,  3.96it/s]

 22%|██▏       | 68/306 [00:20<01:00,  3.96it/s]

 23%|██▎       | 69/306 [00:20<00:59,  3.98it/s]

 23%|██▎       | 70/306 [00:20<01:01,  3.85it/s]

 23%|██▎       | 71/306 [00:21<01:00,  3.86it/s]

 24%|██▎       | 72/306 [00:21<01:00,  3.87it/s]

 24%|██▍       | 73/306 [00:21<01:01,  3.81it/s]

 24%|██▍       | 74/306 [00:21<01:01,  3.78it/s]

 25%|██▍       | 75/306 [00:22<01:00,  3.81it/s]

 25%|██▍       | 76/306 [00:22<01:00,  3.81it/s]

 25%|██▌       | 77/306 [00:22<00:59,  3.86it/s]

 25%|██▌       | 78/306 [00:22<00:59,  3.80it/s]

 26%|██▌       | 79/306 [00:23<00:59,  3.83it/s]

 26%|██▌       | 80/306 [00:23<00:58,  3.84it/s]

 26%|██▋       | 81/306 [00:23<00:57,  3.89it/s]

 27%|██▋       | 82/306 [00:23<00:57,  3.91it/s]

 27%|██▋       | 83/306 [00:24<00:56,  3.93it/s]

 27%|██▋       | 84/306 [00:24<00:56,  3.92it/s]

 28%|██▊       | 85/306 [00:24<00:56,  3.94it/s]

 28%|██▊       | 86/306 [00:25<00:56,  3.86it/s]

 28%|██▊       | 87/306 [00:25<00:56,  3.88it/s]

 29%|██▉       | 88/306 [00:25<00:55,  3.90it/s]

 29%|██▉       | 89/306 [00:25<00:55,  3.92it/s]

 29%|██▉       | 90/306 [00:26<00:54,  3.93it/s]

 30%|██▉       | 91/306 [00:26<00:54,  3.94it/s]

 30%|███       | 92/306 [00:26<00:54,  3.95it/s]

 30%|███       | 93/306 [00:26<00:53,  3.95it/s]

 31%|███       | 94/306 [00:27<00:54,  3.90it/s]

 31%|███       | 95/306 [00:27<00:54,  3.88it/s]

 31%|███▏      | 96/306 [00:27<00:54,  3.86it/s]

 32%|███▏      | 97/306 [00:27<00:53,  3.89it/s]

 32%|███▏      | 98/306 [00:28<00:53,  3.92it/s]

 32%|███▏      | 99/306 [00:28<00:52,  3.94it/s]

 33%|███▎      | 100/306 [00:28<00:52,  3.96it/s]

 33%|███▎      | 101/306 [00:28<00:53,  3.84it/s]

 33%|███▎      | 102/306 [00:29<00:52,  3.85it/s]

 34%|███▎      | 103/306 [00:29<00:52,  3.85it/s]

 34%|███▍      | 104/306 [00:29<00:52,  3.88it/s]

 34%|███▍      | 105/306 [00:29<00:51,  3.88it/s]

 35%|███▍      | 106/306 [00:30<00:51,  3.92it/s]

 35%|███▍      | 107/306 [00:30<00:50,  3.90it/s]

 35%|███▌      | 108/306 [00:30<00:50,  3.93it/s]

 36%|███▌      | 109/306 [00:30<00:50,  3.88it/s]

 36%|███▌      | 110/306 [00:31<00:50,  3.90it/s]

 36%|███▋      | 111/306 [00:31<00:49,  3.91it/s]

 37%|███▋      | 112/306 [00:31<00:49,  3.94it/s]

 37%|███▋      | 113/306 [00:31<00:48,  3.95it/s]

 37%|███▋      | 114/306 [00:32<00:48,  3.98it/s]

 38%|███▊      | 115/306 [00:32<00:47,  3.98it/s]

 38%|███▊      | 116/306 [00:32<00:47,  3.99it/s]

 38%|███▊      | 117/306 [00:32<00:48,  3.90it/s]

 39%|███▊      | 118/306 [00:33<00:48,  3.86it/s]

 39%|███▉      | 119/306 [00:33<00:48,  3.83it/s]

 39%|███▉      | 120/306 [00:33<00:48,  3.85it/s]

 40%|███▉      | 121/306 [00:33<00:47,  3.89it/s]

 40%|███▉      | 122/306 [00:34<00:46,  3.92it/s]

 40%|████      | 123/306 [00:34<00:46,  3.92it/s]

 41%|████      | 124/306 [00:34<00:46,  3.94it/s]

 41%|████      | 125/306 [00:34<00:46,  3.86it/s]

 41%|████      | 126/306 [00:35<00:46,  3.88it/s]

 42%|████▏     | 127/306 [00:35<00:45,  3.91it/s]

 42%|████▏     | 128/306 [00:35<00:45,  3.87it/s]

 42%|████▏     | 129/306 [00:36<00:46,  3.81it/s]

 42%|████▏     | 130/306 [00:36<00:45,  3.83it/s]

 43%|████▎     | 131/306 [00:36<00:45,  3.87it/s]

 43%|████▎     | 132/306 [00:36<00:44,  3.92it/s]

 43%|████▎     | 133/306 [00:37<00:44,  3.85it/s]

 44%|████▍     | 134/306 [00:37<00:44,  3.89it/s]

 44%|████▍     | 135/306 [00:37<00:43,  3.91it/s]

 44%|████▍     | 136/306 [00:37<00:43,  3.94it/s]

 45%|████▍     | 137/306 [00:38<00:42,  3.96it/s]

 45%|████▌     | 138/306 [00:38<00:42,  3.97it/s]

 45%|████▌     | 139/306 [00:38<00:42,  3.93it/s]

 46%|████▌     | 140/306 [00:38<00:42,  3.89it/s]

 46%|████▌     | 141/306 [00:39<00:43,  3.78it/s]

 46%|████▋     | 142/306 [00:39<00:43,  3.81it/s]

 47%|████▋     | 143/306 [00:39<00:42,  3.85it/s]

 47%|████▋     | 144/306 [00:39<00:41,  3.89it/s]

 47%|████▋     | 145/306 [00:40<00:41,  3.92it/s]

 48%|████▊     | 146/306 [00:40<00:40,  3.93it/s]

 48%|████▊     | 147/306 [00:40<00:40,  3.94it/s]

 48%|████▊     | 148/306 [00:40<00:40,  3.94it/s]

 49%|████▊     | 149/306 [00:41<00:40,  3.88it/s]

 49%|████▉     | 150/306 [00:41<00:40,  3.87it/s]

 49%|████▉     | 151/306 [00:41<00:40,  3.86it/s]

 50%|████▉     | 152/306 [00:41<00:40,  3.83it/s]

 50%|█████     | 153/306 [00:42<00:39,  3.84it/s]

 50%|█████     | 154/306 [00:42<00:39,  3.87it/s]

 51%|█████     | 155/306 [00:42<00:38,  3.91it/s]

 51%|█████     | 156/306 [00:42<00:38,  3.93it/s]

 51%|█████▏    | 157/306 [00:43<00:38,  3.90it/s]

 52%|█████▏    | 158/306 [00:43<00:37,  3.91it/s]

 52%|█████▏    | 159/306 [00:43<00:37,  3.94it/s]

 52%|█████▏    | 160/306 [00:43<00:36,  3.95it/s]

 53%|█████▎    | 161/306 [00:44<00:36,  3.96it/s]

 53%|█████▎    | 162/306 [00:44<00:36,  3.90it/s]

 53%|█████▎    | 163/306 [00:44<00:36,  3.90it/s]

 54%|█████▎    | 164/306 [00:45<00:37,  3.75it/s]

 54%|█████▍    | 165/306 [00:45<00:37,  3.80it/s]

 54%|█████▍    | 166/306 [00:45<00:36,  3.84it/s]

 55%|█████▍    | 167/306 [00:45<00:35,  3.88it/s]

 55%|█████▍    | 168/306 [00:46<00:35,  3.90it/s]

 55%|█████▌    | 169/306 [00:46<00:34,  3.92it/s]

 56%|█████▌    | 170/306 [00:46<00:34,  3.91it/s]

 56%|█████▌    | 171/306 [00:46<00:34,  3.93it/s]

 56%|█████▌    | 172/306 [00:47<00:34,  3.86it/s]

 57%|█████▋    | 173/306 [00:47<00:34,  3.90it/s]

 57%|█████▋    | 174/306 [00:47<00:33,  3.90it/s]

 57%|█████▋    | 175/306 [00:47<00:33,  3.91it/s]

 58%|█████▊    | 176/306 [00:48<00:33,  3.88it/s]

 58%|█████▊    | 177/306 [00:48<00:33,  3.90it/s]

 58%|█████▊    | 178/306 [00:48<00:32,  3.91it/s]

 58%|█████▊    | 179/306 [00:48<00:32,  3.93it/s]

 59%|█████▉    | 180/306 [00:49<00:32,  3.88it/s]

 59%|█████▉    | 181/306 [00:49<00:32,  3.89it/s]

 59%|█████▉    | 182/306 [00:49<00:31,  3.91it/s]

 60%|█████▉    | 183/306 [00:49<00:31,  3.93it/s]

 60%|██████    | 184/306 [00:50<00:31,  3.91it/s]

 60%|██████    | 185/306 [00:50<00:31,  3.90it/s]

 61%|██████    | 186/306 [00:50<00:30,  3.87it/s]

 61%|██████    | 187/306 [00:50<00:30,  3.89it/s]

 61%|██████▏   | 188/306 [00:51<00:30,  3.85it/s]

 62%|██████▏   | 189/306 [00:51<00:30,  3.87it/s]

 62%|██████▏   | 190/306 [00:51<00:29,  3.87it/s]

 62%|██████▏   | 191/306 [00:51<00:29,  3.90it/s]

 63%|██████▎   | 192/306 [00:52<00:29,  3.93it/s]

 63%|██████▎   | 193/306 [00:52<00:28,  3.94it/s]

 63%|██████▎   | 194/306 [00:52<00:28,  3.97it/s]

 64%|██████▎   | 195/306 [00:52<00:27,  3.96it/s]

 64%|██████▍   | 196/306 [00:53<00:28,  3.91it/s]

 64%|██████▍   | 197/306 [00:53<00:27,  3.91it/s]

 65%|██████▍   | 198/306 [00:53<00:27,  3.91it/s]

 65%|██████▌   | 199/306 [00:53<00:27,  3.90it/s]

 65%|██████▌   | 200/306 [00:54<00:27,  3.91it/s]

 66%|██████▌   | 201/306 [00:54<00:26,  3.91it/s]

 66%|██████▌   | 202/306 [00:54<00:26,  3.92it/s]

 66%|██████▋   | 203/306 [00:55<00:27,  3.75it/s]

 67%|██████▋   | 204/306 [00:55<00:26,  3.79it/s]

 67%|██████▋   | 205/306 [00:55<00:26,  3.83it/s]

 67%|██████▋   | 206/306 [00:55<00:25,  3.86it/s]

 68%|██████▊   | 207/306 [00:56<00:25,  3.83it/s]

 68%|██████▊   | 208/306 [00:56<00:25,  3.81it/s]

 68%|██████▊   | 209/306 [00:56<00:25,  3.84it/s]

 69%|██████▊   | 210/306 [00:56<00:24,  3.86it/s]

 69%|██████▉   | 211/306 [00:57<00:24,  3.84it/s]

 69%|██████▉   | 212/306 [00:57<00:24,  3.87it/s]

 70%|██████▉   | 213/306 [00:57<00:23,  3.90it/s]

 70%|██████▉   | 214/306 [00:57<00:23,  3.93it/s]

 70%|███████   | 215/306 [00:58<00:22,  3.96it/s]

 71%|███████   | 216/306 [00:58<00:22,  3.97it/s]

 71%|███████   | 217/306 [00:58<00:22,  3.94it/s]

 71%|███████   | 218/306 [00:58<00:22,  3.94it/s]

 72%|███████▏  | 219/306 [00:59<00:22,  3.95it/s]

 72%|███████▏  | 220/306 [00:59<00:22,  3.82it/s]

 72%|███████▏  | 221/306 [00:59<00:22,  3.80it/s]

 73%|███████▎  | 222/306 [00:59<00:22,  3.77it/s]

 73%|███████▎  | 223/306 [01:00<00:21,  3.78it/s]

 73%|███████▎  | 224/306 [01:00<00:21,  3.77it/s]

 74%|███████▎  | 225/306 [01:00<00:21,  3.76it/s]

 74%|███████▍  | 226/306 [01:01<00:21,  3.78it/s]

 74%|███████▍  | 227/306 [01:01<00:20,  3.81it/s]

 75%|███████▍  | 228/306 [01:01<00:20,  3.75it/s]

 75%|███████▍  | 229/306 [01:01<00:20,  3.74it/s]

 75%|███████▌  | 230/306 [01:02<00:20,  3.72it/s]

 75%|███████▌  | 231/306 [01:02<00:19,  3.75it/s]

 76%|███████▌  | 232/306 [01:02<00:19,  3.81it/s]

 76%|███████▌  | 233/306 [01:02<00:18,  3.85it/s]

 76%|███████▋  | 234/306 [01:03<00:18,  3.89it/s]

 77%|███████▋  | 235/306 [01:03<00:18,  3.89it/s]

 77%|███████▋  | 236/306 [01:03<00:18,  3.88it/s]

 77%|███████▋  | 237/306 [01:03<00:17,  3.89it/s]

 78%|███████▊  | 238/306 [01:04<00:17,  3.92it/s]

 78%|███████▊  | 239/306 [01:04<00:17,  3.91it/s]

 78%|███████▊  | 240/306 [01:04<00:16,  3.92it/s]

 79%|███████▉  | 241/306 [01:04<00:16,  3.95it/s]

 79%|███████▉  | 242/306 [01:05<00:16,  3.96it/s]

 79%|███████▉  | 243/306 [01:05<00:15,  3.96it/s]

 80%|███████▉  | 244/306 [01:05<00:15,  3.88it/s]

 80%|████████  | 245/306 [01:05<00:15,  3.89it/s]

 80%|████████  | 246/306 [01:06<00:15,  3.87it/s]

 81%|████████  | 247/306 [01:06<00:15,  3.85it/s]

 81%|████████  | 248/306 [01:06<00:15,  3.83it/s]

 81%|████████▏ | 249/306 [01:06<00:14,  3.81it/s]

 82%|████████▏ | 250/306 [01:07<00:14,  3.82it/s]

 82%|████████▏ | 251/306 [01:07<00:14,  3.83it/s]

 82%|████████▏ | 252/306 [01:07<00:14,  3.75it/s]

 83%|████████▎ | 253/306 [01:08<00:13,  3.79it/s]

 83%|████████▎ | 254/306 [01:08<00:13,  3.84it/s]

 83%|████████▎ | 255/306 [01:08<00:13,  3.89it/s]

 84%|████████▎ | 256/306 [01:08<00:12,  3.92it/s]

 84%|████████▍ | 257/306 [01:09<00:12,  3.94it/s]

 84%|████████▍ | 258/306 [01:09<00:12,  3.96it/s]

 85%|████████▍ | 259/306 [01:09<00:11,  3.97it/s]

 85%|████████▍ | 260/306 [01:09<00:11,  3.87it/s]

 85%|████████▌ | 261/306 [01:10<00:11,  3.90it/s]

 86%|████████▌ | 262/306 [01:10<00:11,  3.89it/s]

 86%|████████▌ | 263/306 [01:10<00:10,  3.92it/s]

 86%|████████▋ | 264/306 [01:10<00:10,  3.93it/s]

 87%|████████▋ | 265/306 [01:11<00:10,  3.95it/s]

 87%|████████▋ | 266/306 [01:11<00:10,  3.92it/s]

 87%|████████▋ | 267/306 [01:11<00:09,  3.91it/s]

 88%|████████▊ | 268/306 [01:11<00:09,  3.85it/s]

 88%|████████▊ | 269/306 [01:12<00:09,  3.84it/s]

 88%|████████▊ | 270/306 [01:12<00:09,  3.87it/s]

 89%|████████▊ | 271/306 [01:12<00:08,  3.89it/s]

 89%|████████▉ | 272/306 [01:12<00:08,  3.82it/s]

 89%|████████▉ | 273/306 [01:13<00:08,  3.83it/s]

 90%|████████▉ | 274/306 [01:13<00:08,  3.82it/s]

 90%|████████▉ | 275/306 [01:13<00:08,  3.86it/s]

 90%|█████████ | 276/306 [01:13<00:07,  3.91it/s]

 91%|█████████ | 277/306 [01:14<00:07,  3.92it/s]

 91%|█████████ | 278/306 [01:14<00:07,  3.94it/s]

 91%|█████████ | 279/306 [01:14<00:06,  3.97it/s]

 92%|█████████▏| 280/306 [01:14<00:06,  3.98it/s]

 92%|█████████▏| 281/306 [01:15<00:06,  3.99it/s]

 92%|█████████▏| 282/306 [01:15<00:05,  4.00it/s]

 92%|█████████▏| 283/306 [01:15<00:05,  4.00it/s]

 93%|█████████▎| 284/306 [01:15<00:05,  4.00it/s]

 93%|█████████▎| 285/306 [01:16<00:05,  3.84it/s]

 93%|█████████▎| 286/306 [01:16<00:05,  3.88it/s]

 94%|█████████▍| 287/306 [01:16<00:04,  3.91it/s]

 94%|█████████▍| 288/306 [01:16<00:04,  3.94it/s]

 94%|█████████▍| 289/306 [01:17<00:04,  3.94it/s]

 95%|█████████▍| 290/306 [01:17<00:04,  3.94it/s]

 95%|█████████▌| 291/306 [01:17<00:03,  3.93it/s]

 95%|█████████▌| 292/306 [01:17<00:03,  3.94it/s]

 96%|█████████▌| 293/306 [01:18<00:03,  3.87it/s]

 96%|█████████▌| 294/306 [01:18<00:03,  3.90it/s]

 96%|█████████▋| 295/306 [01:18<00:02,  3.88it/s]

 97%|█████████▋| 296/306 [01:19<00:02,  3.87it/s]

 97%|█████████▋| 297/306 [01:19<00:02,  3.83it/s]

 97%|█████████▋| 298/306 [01:19<00:02,  3.85it/s]

 98%|█████████▊| 299/306 [01:19<00:01,  3.89it/s]

 98%|█████████▊| 300/306 [01:20<00:01,  3.93it/s]

 98%|█████████▊| 301/306 [01:20<00:01,  3.95it/s]

 99%|█████████▊| 302/306 [01:20<00:01,  3.93it/s]

 99%|█████████▉| 303/306 [01:20<00:00,  3.95it/s]

 99%|█████████▉| 304/306 [01:21<00:00,  3.97it/s]

100%|█████████▉| 305/306 [01:21<00:00,  3.94it/s]

100%|██████████| 306/306 [01:21<00:00,  3.96it/s]

100%|██████████| 306/306 [01:21<00:00,  3.75it/s]

convnext Epoch 1 loss 1.8349 val_acc 0.6695

Saved best convnext to /kaggle/working/writer_convnext_best.pth

  0%|          | 0/306 [00:00<?, ?it/s]

  0%|          | 1/306 [00:03<16:41,  3.28s/it]

  1%|          | 2/306 [00:03<07:37,  1.50s/it]

  1%|          | 3/306 [00:03<04:41,  1.08it/s]

  1%|▏         | 4/306 [00:04<03:19,  1.52it/s]

  2%|▏         | 5/306 [00:04<02:33,  1.96it/s]

  2%|▏         | 6/306 [00:04<02:06,  2.37it/s]

  2%|▏         | 7/306 [00:04<01:50,  2.72it/s]

  3%|▎         | 8/306 [00:05<01:43,  2.87it/s]

  3%|▎         | 9/306 [00:05<01:35,  3.12it/s]

  3%|▎         | 10/306 [00:05<01:29,  3.32it/s]

  4%|▎         | 11/306 [00:05<01:24,  3.50it/s]

  4%|▍         | 12/306 [00:06<01:20,  3.64it/s]

  4%|▍         | 13/306 [00:06<01:17,  3.76it/s]

  5%|▍         | 14/306 [00:06<01:16,  3.84it/s]

  5%|▍         | 15/306 [00:06<01:14,  3.90it/s]

  5%|▌         | 16/306 [00:07<01:15,  3.86it/s]

  6%|▌         | 17/306 [00:07<01:13,  3.91it/s]

  6%|▌         | 18/306 [00:07<01:12,  3.95it/s]

  6%|▌         | 19/306 [00:07<01:11,  3.99it/s]

  7%|▋         | 20/306 [00:08<01:11,  4.00it/s]

  7%|▋         | 21/306 [00:08<01:10,  4.02it/s]

  7%|▋         | 22/306 [00:08<01:10,  4.03it/s]

  8%|▊         | 23/306 [00:08<01:10,  4.04it/s]

  8%|▊         | 24/306 [00:09<01:09,  4.05it/s]

  8%|▊         | 25/306 [00:09<01:13,  3.83it/s]

  8%|▊         | 26/306 [00:09<01:11,  3.90it/s]

  9%|▉         | 27/306 [00:09<01:10,  3.96it/s]

  9%|▉         | 28/306 [00:10<01:09,  3.99it/s]

  9%|▉         | 29/306 [00:10<01:08,  4.02it/s]

 10%|▉         | 30/306 [00:10<01:08,  4.00it/s]

 10%|█         | 31/306 [00:10<01:08,  4.01it/s]

 10%|█         | 32/306 [00:11<01:09,  3.97it/s]

 11%|█         | 33/306 [00:11<01:11,  3.84it/s]

 11%|█         | 34/306 [00:11<01:09,  3.90it/s]

 11%|█▏        | 35/306 [00:11<01:08,  3.94it/s]

 12%|█▏        | 36/306 [00:12<01:07,  3.97it/s]

 12%|█▏        | 37/306 [00:12<01:07,  4.00it/s]

 12%|█▏        | 38/306 [00:12<01:06,  4.02it/s]

 13%|█▎        | 39/306 [00:12<01:06,  4.04it/s]

 13%|█▎        | 40/306 [00:13<01:05,  4.05it/s]

 13%|█▎        | 41/306 [00:13<01:09,  3.81it/s]

 14%|█▎        | 42/306 [00:13<01:08,  3.87it/s]

 14%|█▍        | 43/306 [00:13<01:06,  3.94it/s]

 14%|█▍        | 44/306 [00:14<01:05,  3.97it/s]

 15%|█▍        | 45/306 [00:14<01:05,  4.01it/s]

 15%|█▌        | 46/306 [00:14<01:04,  4.03it/s]

 15%|█▌        | 47/306 [00:14<01:03,  4.05it/s]

 16%|█▌        | 48/306 [00:15<01:03,  4.05it/s]

 16%|█▌        | 49/306 [00:15<01:04,  3.99it/s]

 16%|█▋        | 50/306 [00:15<01:03,  4.01it/s]

 17%|█▋        | 51/306 [00:15<01:03,  4.03it/s]

 17%|█▋        | 52/306 [00:16<01:02,  4.05it/s]

 17%|█▋        | 53/306 [00:16<01:02,  4.07it/s]

 18%|█▊        | 54/306 [00:16<01:02,  4.03it/s]

 18%|█▊        | 55/306 [00:16<01:02,  4.00it/s]

 18%|█▊        | 56/306 [00:17<01:03,  3.96it/s]

 19%|█▊        | 57/306 [00:17<01:04,  3.84it/s]

 19%|█▉        | 58/306 [00:17<01:03,  3.90it/s]

 19%|█▉        | 59/306 [00:17<01:02,  3.96it/s]

 20%|█▉        | 60/306 [00:18<01:01,  4.00it/s]

 20%|█▉        | 61/306 [00:18<01:00,  4.02it/s]

 20%|██        | 62/306 [00:18<01:00,  4.04it/s]

 21%|██        | 63/306 [00:18<00:59,  4.06it/s]

 21%|██        | 64/306 [00:19<00:59,  4.06it/s]

 21%|██        | 65/306 [00:19<01:02,  3.85it/s]

 22%|██▏       | 66/306 [00:19<01:01,  3.90it/s]

 22%|██▏       | 67/306 [00:19<01:00,  3.93it/s]

 22%|██▏       | 68/306 [00:20<00:59,  3.97it/s]

 23%|██▎       | 69/306 [00:20<00:59,  4.01it/s]

 23%|██▎       | 70/306 [00:20<00:58,  4.03it/s]

 23%|██▎       | 71/306 [00:20<00:58,  4.05it/s]

 24%|██▎       | 72/306 [00:21<00:57,  4.05it/s]

 24%|██▍       | 73/306 [00:21<01:00,  3.86it/s]

 24%|██▍       | 74/306 [00:21<00:59,  3.92it/s]

 25%|██▍       | 75/306 [00:21<00:58,  3.97it/s]

 25%|██▍       | 76/306 [00:22<00:57,  3.99it/s]

 25%|██▌       | 77/306 [00:22<00:57,  3.98it/s]

 25%|██▌       | 78/306 [00:22<00:57,  3.93it/s]

 26%|██▌       | 79/306 [00:22<00:57,  3.97it/s]

 26%|██▌       | 80/306 [00:23<00:56,  3.99it/s]

 26%|██▋       | 81/306 [00:23<00:59,  3.76it/s]

 27%|██▋       | 82/306 [00:23<00:57,  3.87it/s]

 27%|██▋       | 83/306 [00:23<00:56,  3.95it/s]

 27%|██▋       | 84/306 [00:24<00:55,  4.00it/s]

 28%|██▊       | 85/306 [00:24<00:54,  4.04it/s]

 28%|██▊       | 86/306 [00:24<00:54,  4.06it/s]

 28%|██▊       | 87/306 [00:24<00:53,  4.08it/s]

 29%|██▉       | 88/306 [00:25<00:53,  4.09it/s]

 29%|██▉       | 89/306 [00:25<00:59,  3.62it/s]

 29%|██▉       | 90/306 [00:25<00:57,  3.75it/s]

 30%|██▉       | 91/306 [00:26<00:56,  3.83it/s]

 30%|███       | 92/306 [00:26<00:54,  3.89it/s]

 30%|███       | 93/306 [00:26<00:53,  3.96it/s]

 31%|███       | 94/306 [00:26<00:52,  4.01it/s]

 31%|███       | 95/306 [00:27<00:52,  4.05it/s]

 31%|███▏      | 96/306 [00:27<00:51,  4.06it/s]

 32%|███▏      | 97/306 [00:27<00:57,  3.63it/s]

 32%|███▏      | 98/306 [00:27<00:55,  3.76it/s]

 32%|███▏      | 99/306 [00:28<00:53,  3.84it/s]

 33%|███▎      | 100/306 [00:28<00:53,  3.88it/s]

 33%|███▎      | 101/306 [00:28<00:52,  3.93it/s]

 33%|███▎      | 102/306 [00:28<00:51,  3.97it/s]

 34%|███▎      | 103/306 [00:29<00:50,  4.01it/s]

 34%|███▍      | 104/306 [00:29<00:50,  4.04it/s]

 34%|███▍      | 105/306 [00:29<00:57,  3.52it/s]

 35%|███▍      | 106/306 [00:29<00:54,  3.69it/s]

 35%|███▍      | 107/306 [00:30<00:52,  3.80it/s]

 35%|███▌      | 108/306 [00:30<00:51,  3.88it/s]

 36%|███▌      | 109/306 [00:30<00:49,  3.95it/s]

 36%|███▌      | 110/306 [00:30<00:48,  4.00it/s]

 36%|███▋      | 111/306 [00:31<00:48,  4.04it/s]

 37%|███▋      | 112/306 [00:31<00:47,  4.07it/s]

 37%|███▋      | 113/306 [00:31<00:54,  3.57it/s]

 37%|███▋      | 114/306 [00:31<00:51,  3.72it/s]

 38%|███▊      | 115/306 [00:32<00:50,  3.79it/s]

 38%|███▊      | 116/306 [00:32<00:49,  3.86it/s]

 38%|███▊      | 117/306 [00:32<00:48,  3.93it/s]

 39%|███▊      | 118/306 [00:32<00:47,  3.99it/s]

 39%|███▉      | 119/306 [00:33<00:46,  4.02it/s]

 39%|███▉      | 120/306 [00:33<00:45,  4.05it/s]

 40%|███▉      | 121/306 [00:33<00:47,  3.90it/s]

 40%|███▉      | 122/306 [00:33<00:47,  3.89it/s]

 40%|████      | 123/306 [00:34<00:47,  3.87it/s]

 41%|████      | 124/306 [00:34<00:46,  3.91it/s]

 41%|████      | 125/306 [00:34<00:45,  3.95it/s]

 41%|████      | 126/306 [00:34<00:44,  4.01it/s]

 42%|████▏     | 127/306 [00:35<00:44,  4.03it/s]

 42%|████▏     | 128/306 [00:35<00:43,  4.05it/s]

 42%|████▏     | 129/306 [00:35<00:44,  3.96it/s]

 42%|████▏     | 130/306 [00:35<00:43,  4.01it/s]

 43%|████▎     | 131/306 [00:36<00:43,  4.02it/s]

 43%|████▎     | 132/306 [00:36<00:42,  4.05it/s]

 43%|████▎     | 133/306 [00:36<00:42,  4.08it/s]

 44%|████▍     | 134/306 [00:36<00:42,  4.10it/s]

 44%|████▍     | 135/306 [00:37<00:41,  4.11it/s]

 44%|████▍     | 136/306 [00:37<00:41,  4.11it/s]

 45%|████▍     | 137/306 [00:37<00:42,  3.95it/s]

 45%|████▌     | 138/306 [00:37<00:42,  3.96it/s]

 45%|████▌     | 139/306 [00:38<00:41,  3.99it/s]

 46%|████▌     | 140/306 [00:38<00:41,  4.00it/s]

 46%|████▌     | 141/306 [00:38<00:41,  4.01it/s]

 46%|████▋     | 142/306 [00:38<00:40,  4.04it/s]

 47%|████▋     | 143/306 [00:39<00:40,  4.05it/s]

 47%|████▋     | 144/306 [00:39<00:39,  4.07it/s]

 47%|████▋     | 145/306 [00:39<00:42,  3.77it/s]

 48%|████▊     | 146/306 [00:40<00:41,  3.84it/s]

 48%|████▊     | 147/306 [00:40<00:40,  3.91it/s]

 48%|████▊     | 148/306 [00:40<00:39,  3.96it/s]

 49%|████▊     | 149/306 [00:40<00:39,  4.00it/s]

 49%|████▉     | 150/306 [00:40<00:38,  4.04it/s]

 49%|████▉     | 151/306 [00:41<00:38,  4.06it/s]

 50%|████▉     | 152/306 [00:41<00:37,  4.06it/s]

 50%|█████     | 153/306 [00:41<00:39,  3.87it/s]

 50%|█████     | 154/306 [00:42<00:38,  3.94it/s]

 51%|█████     | 155/306 [00:42<00:37,  3.98it/s]

 51%|█████     | 156/306 [00:42<00:37,  4.02it/s]

 51%|█████▏    | 157/306 [00:42<00:37,  4.02it/s]

 52%|█████▏    | 158/306 [00:42<00:36,  4.05it/s]

 52%|█████▏    | 159/306 [00:43<00:36,  4.06it/s]

 52%|█████▏    | 160/306 [00:43<00:35,  4.07it/s]

 53%|█████▎    | 161/306 [00:43<00:37,  3.91it/s]

 53%|█████▎    | 162/306 [00:44<00:36,  3.97it/s]

 53%|█████▎    | 163/306 [00:44<00:35,  3.98it/s]

 54%|█████▎    | 164/306 [00:44<00:35,  4.01it/s]

 54%|█████▍    | 165/306 [00:44<00:34,  4.03it/s]

 54%|█████▍    | 166/306 [00:44<00:34,  4.05it/s]

 55%|█████▍    | 167/306 [00:45<00:34,  4.03it/s]

 55%|█████▍    | 168/306 [00:45<00:34,  4.02it/s]

 55%|█████▌    | 169/306 [00:45<00:35,  3.84it/s]

 56%|█████▌    | 170/306 [00:46<00:34,  3.90it/s]

 56%|█████▌    | 171/306 [00:46<00:34,  3.92it/s]

 56%|█████▌    | 172/306 [00:46<00:33,  3.96it/s]

 57%|█████▋    | 173/306 [00:46<00:33,  4.00it/s]

 57%|█████▋    | 174/306 [00:47<00:32,  4.03it/s]

 57%|█████▋    | 175/306 [00:47<00:32,  4.05it/s]

 58%|█████▊    | 176/306 [00:47<00:32,  3.95it/s]

 58%|█████▊    | 177/306 [00:47<00:32,  3.97it/s]

 58%|█████▊    | 178/306 [00:48<00:32,  4.00it/s]

 58%|█████▊    | 179/306 [00:48<00:31,  4.04it/s]

 59%|█████▉    | 180/306 [00:48<00:31,  4.04it/s]

 59%|█████▉    | 181/306 [00:48<00:30,  4.05it/s]

 59%|█████▉    | 182/306 [00:48<00:30,  4.06it/s]

 60%|█████▉    | 183/306 [00:49<00:30,  4.08it/s]

 60%|██████    | 184/306 [00:49<00:30,  3.98it/s]

 60%|██████    | 185/306 [00:49<00:30,  3.97it/s]

 61%|██████    | 186/306 [00:49<00:29,  4.01it/s]

 61%|██████    | 187/306 [00:50<00:29,  4.03it/s]

 61%|██████▏   | 188/306 [00:50<00:29,  4.05it/s]

 62%|██████▏   | 189/306 [00:50<00:29,  4.03it/s]

 62%|██████▏   | 190/306 [00:50<00:28,  4.01it/s]

 62%|██████▏   | 191/306 [00:51<00:28,  4.00it/s]

 63%|██████▎   | 192/306 [00:51<00:28,  3.99it/s]

 63%|██████▎   | 193/306 [00:51<00:29,  3.80it/s]

 63%|██████▎   | 194/306 [00:52<00:28,  3.87it/s]

 64%|██████▎   | 195/306 [00:52<00:28,  3.93it/s]

 64%|██████▍   | 196/306 [00:52<00:27,  3.98it/s]

 64%|██████▍   | 197/306 [00:52<00:27,  4.02it/s]

 65%|██████▍   | 198/306 [00:53<00:26,  4.04it/s]

 65%|██████▌   | 199/306 [00:53<00:26,  4.06it/s]

 65%|██████▌   | 200/306 [00:53<00:26,  4.07it/s]

 66%|██████▌   | 201/306 [00:53<00:27,  3.85it/s]

 66%|██████▌   | 202/306 [00:54<00:26,  3.92it/s]

 66%|██████▋   | 203/306 [00:54<00:25,  3.97it/s]

 67%|██████▋   | 204/306 [00:54<00:25,  4.01it/s]

 67%|██████▋   | 205/306 [00:54<00:25,  4.02it/s]

 67%|██████▋   | 206/306 [00:55<00:24,  4.05it/s]

 68%|██████▊   | 207/306 [00:55<00:24,  4.05it/s]

 68%|██████▊   | 208/306 [00:55<00:24,  4.06it/s]

 68%|██████▊   | 209/306 [00:55<00:24,  3.90it/s]

 69%|██████▊   | 210/306 [00:56<00:24,  3.94it/s]

 69%|██████▉   | 211/306 [00:56<00:23,  3.98it/s]

 69%|██████▉   | 212/306 [00:56<00:23,  3.99it/s]

 70%|██████▉   | 213/306 [00:56<00:23,  3.96it/s]

 70%|██████▉   | 214/306 [00:57<00:23,  3.94it/s]

 70%|███████   | 215/306 [00:57<00:23,  3.95it/s]

 71%|███████   | 216/306 [00:57<00:22,  3.94it/s]

 71%|███████   | 217/306 [00:57<00:23,  3.87it/s]

 71%|███████   | 218/306 [00:58<00:22,  3.91it/s]

 72%|███████▏  | 219/306 [00:58<00:22,  3.94it/s]

 72%|███████▏  | 220/306 [00:58<00:21,  3.98it/s]

 72%|███████▏  | 221/306 [00:58<00:21,  4.02it/s]

 73%|███████▎  | 222/306 [00:59<00:20,  4.05it/s]

 73%|███████▎  | 223/306 [00:59<00:20,  4.07it/s]

 73%|███████▎  | 224/306 [00:59<00:20,  4.07it/s]

 74%|███████▎  | 225/306 [00:59<00:20,  3.88it/s]

 74%|███████▍  | 226/306 [01:00<00:20,  3.94it/s]

 74%|███████▍  | 227/306 [01:00<00:19,  3.99it/s]

 75%|███████▍  | 228/306 [01:00<00:19,  4.03it/s]

 75%|███████▍  | 229/306 [01:00<00:18,  4.06it/s]

 75%|███████▌  | 230/306 [01:01<00:18,  4.07it/s]

 75%|███████▌  | 231/306 [01:01<00:18,  4.08it/s]

 76%|███████▌  | 232/306 [01:01<00:18,  4.07it/s]

 76%|███████▌  | 233/306 [01:01<00:18,  3.90it/s]

 76%|███████▋  | 234/306 [01:02<00:18,  3.95it/s]

 77%|███████▋  | 235/306 [01:02<00:17,  3.97it/s]

 77%|███████▋  | 236/306 [01:02<00:17,  3.98it/s]

 77%|███████▋  | 237/306 [01:02<00:17,  3.97it/s]

 78%|███████▊  | 238/306 [01:03<00:16,  4.01it/s]

 78%|███████▊  | 239/306 [01:03<00:16,  3.98it/s]

 78%|███████▊  | 240/306 [01:03<00:16,  3.97it/s]

 79%|███████▉  | 241/306 [01:03<00:17,  3.82it/s]

 79%|███████▉  | 242/306 [01:04<00:16,  3.87it/s]

 79%|███████▉  | 243/306 [01:04<00:16,  3.92it/s]

 80%|███████▉  | 244/306 [01:04<00:15,  3.95it/s]

 80%|████████  | 245/306 [01:04<00:15,  4.00it/s]

 80%|████████  | 246/306 [01:05<00:14,  4.01it/s]

 81%|████████  | 247/306 [01:05<00:14,  4.03it/s]

 81%|████████  | 248/306 [01:05<00:15,  3.85it/s]

 81%|████████▏ | 249/306 [01:05<00:14,  3.90it/s]

 82%|████████▏ | 250/306 [01:06<00:14,  3.92it/s]

 82%|████████▏ | 251/306 [01:06<00:14,  3.92it/s]

 82%|████████▏ | 252/306 [01:06<00:13,  3.94it/s]

 83%|████████▎ | 253/306 [01:06<00:13,  3.98it/s]

 83%|████████▎ | 254/306 [01:07<00:12,  4.00it/s]

 83%|████████▎ | 255/306 [01:07<00:12,  4.02it/s]

 84%|████████▎ | 256/306 [01:07<00:12,  3.93it/s]

 84%|████████▍ | 257/306 [01:07<00:12,  3.98it/s]

 84%|████████▍ | 258/306 [01:08<00:12,  3.96it/s]

 85%|████████▍ | 259/306 [01:08<00:11,  3.97it/s]

 85%|████████▍ | 260/306 [01:08<00:11,  4.00it/s]

 85%|████████▌ | 261/306 [01:08<00:11,  4.03it/s]

 86%|████████▌ | 262/306 [01:09<00:10,  4.04it/s]

 86%|████████▌ | 263/306 [01:09<00:10,  4.02it/s]

 86%|████████▋ | 264/306 [01:09<00:10,  3.97it/s]

 87%|████████▋ | 265/306 [01:09<00:10,  3.93it/s]

 87%|████████▋ | 266/306 [01:10<00:10,  3.92it/s]

 87%|████████▋ | 267/306 [01:10<00:09,  3.95it/s]

 88%|████████▊ | 268/306 [01:10<00:09,  3.97it/s]

 88%|████████▊ | 269/306 [01:10<00:09,  3.99it/s]

 88%|████████▊ | 270/306 [01:11<00:08,  4.00it/s]

 89%|████████▊ | 271/306 [01:11<00:08,  4.03it/s]

 89%|████████▉ | 272/306 [01:11<00:08,  3.94it/s]

 89%|████████▉ | 273/306 [01:11<00:08,  3.92it/s]

 90%|████████▉ | 274/306 [01:12<00:08,  3.89it/s]

 90%|████████▉ | 275/306 [01:12<00:07,  3.93it/s]

 90%|█████████ | 276/306 [01:12<00:07,  3.96it/s]

 91%|█████████ | 277/306 [01:12<00:07,  3.99it/s]

 91%|█████████ | 278/306 [01:13<00:06,  4.01it/s]

 91%|█████████ | 279/306 [01:13<00:06,  4.00it/s]

 92%|█████████▏| 280/306 [01:13<00:06,  3.89it/s]

 92%|█████████▏| 281/306 [01:13<00:06,  3.91it/s]

 92%|█████████▏| 282/306 [01:14<00:06,  3.91it/s]

 92%|█████████▏| 283/306 [01:14<00:05,  3.96it/s]

 93%|█████████▎| 284/306 [01:14<00:05,  4.00it/s]

 93%|█████████▎| 285/306 [01:14<00:05,  4.03it/s]

 93%|█████████▎| 286/306 [01:15<00:04,  4.05it/s]

 94%|█████████▍| 287/306 [01:15<00:04,  4.05it/s]

 94%|█████████▍| 288/306 [01:15<00:04,  3.90it/s]

 94%|█████████▍| 289/306 [01:15<00:04,  3.92it/s]

 95%|█████████▍| 290/306 [01:16<00:04,  3.92it/s]

 95%|█████████▌| 291/306 [01:16<00:03,  3.93it/s]

 95%|█████████▌| 292/306 [01:16<00:03,  3.94it/s]

 96%|█████████▌| 293/306 [01:16<00:03,  3.96it/s]

 96%|█████████▌| 294/306 [01:17<00:03,  3.97it/s]

 96%|█████████▋| 295/306 [01:17<00:02,  3.98it/s]

 97%|█████████▋| 296/306 [01:17<00:02,  3.91it/s]

 97%|█████████▋| 297/306 [01:17<00:02,  3.93it/s]

 97%|█████████▋| 298/306 [01:18<00:02,  3.95it/s]

 98%|█████████▊| 299/306 [01:18<00:01,  3.89it/s]

 98%|█████████▊| 300/306 [01:18<00:01,  3.92it/s]

 98%|█████████▊| 301/306 [01:18<00:01,  3.95it/s]

 99%|█████████▊| 302/306 [01:19<00:01,  3.97it/s]

 99%|█████████▉| 303/306 [01:19<00:00,  3.94it/s]

 99%|█████████▉| 304/306 [01:19<00:00,  3.91it/s]

100%|█████████▉| 305/306 [01:20<00:00,  3.91it/s]

100%|██████████| 306/306 [01:20<00:00,  3.92it/s]

100%|██████████| 306/306 [01:20<00:00,  3.81it/s]

convnext Epoch 2 loss 1.4550 val_acc 0.7628

Saved best convnext to /kaggle/working/writer_convnext_best.pth

  0%|          | 0/306 [00:00<?, ?it/s]

  0%|          | 1/306 [00:03<16:37,  3.27s/it]

  1%|          | 2/306 [00:03<07:35,  1.50s/it]

  1%|          | 3/306 [00:03<04:41,  1.08it/s]

  1%|▏         | 4/306 [00:04<03:19,  1.51it/s]

  2%|▏         | 5/306 [00:04<02:33,  1.96it/s]

  2%|▏         | 6/306 [00:04<02:06,  2.37it/s]

  2%|▏         | 7/306 [00:04<01:49,  2.74it/s]

  3%|▎         | 8/306 [00:05<01:38,  3.02it/s]

  3%|▎         | 9/306 [00:05<01:31,  3.23it/s]

  3%|▎         | 10/306 [00:05<01:26,  3.42it/s]

  4%|▎         | 11/306 [00:05<01:22,  3.57it/s]

  4%|▍         | 12/306 [00:06<01:19,  3.68it/s]

  4%|▍         | 13/306 [00:06<01:17,  3.80it/s]

  5%|▍         | 14/306 [00:06<01:15,  3.88it/s]

  5%|▍         | 15/306 [00:06<01:13,  3.95it/s]

  5%|▌         | 16/306 [00:07<01:14,  3.90it/s]

  6%|▌         | 17/306 [00:07<01:13,  3.95it/s]

  6%|▌         | 18/306 [00:07<01:12,  3.96it/s]

  6%|▌         | 19/306 [00:07<01:11,  4.00it/s]

  7%|▋         | 20/306 [00:08<01:11,  4.02it/s]

  7%|▋         | 21/306 [00:08<01:11,  4.01it/s]

  7%|▋         | 22/306 [00:08<01:11,  3.99it/s]

  8%|▊         | 23/306 [00:08<01:10,  3.99it/s]

  8%|▊         | 24/306 [00:09<01:12,  3.87it/s]

  8%|▊         | 25/306 [00:09<01:12,  3.89it/s]

  8%|▊         | 26/306 [00:09<01:11,  3.91it/s]

  9%|▉         | 27/306 [00:09<01:10,  3.94it/s]

  9%|▉         | 28/306 [00:10<01:10,  3.97it/s]

  9%|▉         | 29/306 [00:10<01:09,  3.98it/s]

 10%|▉         | 30/306 [00:10<01:09,  3.98it/s]

 10%|█         | 31/306 [00:10<01:09,  3.98it/s]

 10%|█         | 32/306 [00:11<01:09,  3.94it/s]

 11%|█         | 33/306 [00:11<01:09,  3.92it/s]

 11%|█         | 34/306 [00:11<01:09,  3.90it/s]

 11%|█▏        | 35/306 [00:11<01:09,  3.88it/s]

 12%|█▏        | 36/306 [00:12<01:09,  3.89it/s]

 12%|█▏        | 37/306 [00:12<01:09,  3.87it/s]

 12%|█▏        | 38/306 [00:12<01:09,  3.88it/s]

 13%|█▎        | 39/306 [00:12<01:10,  3.80it/s]

 13%|█▎        | 40/306 [00:13<01:09,  3.80it/s]

 13%|█▎        | 41/306 [00:13<01:09,  3.83it/s]

 14%|█▎        | 42/306 [00:13<01:08,  3.87it/s]

 14%|█▍        | 43/306 [00:13<01:08,  3.86it/s]

 14%|█▍        | 44/306 [00:14<01:07,  3.91it/s]

 15%|█▍        | 45/306 [00:14<01:06,  3.92it/s]

 15%|█▌        | 46/306 [00:14<01:05,  3.94it/s]

 15%|█▌        | 47/306 [00:14<01:06,  3.88it/s]

 16%|█▌        | 48/306 [00:15<01:05,  3.93it/s]

 16%|█▌        | 49/306 [00:15<01:05,  3.94it/s]

 16%|█▋        | 50/306 [00:15<01:04,  3.98it/s]

 17%|█▋        | 51/306 [00:15<01:03,  4.01it/s]

 17%|█▋        | 52/306 [00:16<01:02,  4.04it/s]

 17%|█▋        | 53/306 [00:16<01:02,  4.06it/s]

 18%|█▊        | 54/306 [00:16<01:02,  4.06it/s]

 18%|█▊        | 55/306 [00:16<01:03,  3.98it/s]

 18%|█▊        | 56/306 [00:17<01:02,  3.99it/s]

 19%|█▊        | 57/306 [00:17<01:02,  4.01it/s]

 19%|█▉        | 58/306 [00:17<01:01,  4.02it/s]

 19%|█▉        | 59/306 [00:17<01:01,  4.03it/s]

 20%|█▉        | 60/306 [00:18<01:01,  4.01it/s]

 20%|█▉        | 61/306 [00:18<01:01,  3.99it/s]

 20%|██        | 62/306 [00:18<01:01,  3.97it/s]

 21%|██        | 63/306 [00:18<01:02,  3.89it/s]

 21%|██        | 64/306 [00:19<01:01,  3.93it/s]

 21%|██        | 65/306 [00:19<01:01,  3.95it/s]

 22%|██▏       | 66/306 [00:19<01:00,  3.98it/s]

 22%|██▏       | 67/306 [00:19<00:59,  4.01it/s]

 22%|██▏       | 68/306 [00:20<00:59,  4.03it/s]

 23%|██▎       | 69/306 [00:20<00:58,  4.05it/s]

 23%|██▎       | 70/306 [00:20<00:58,  4.05it/s]

 23%|██▎       | 71/306 [00:20<00:58,  4.00it/s]

 24%|██▎       | 72/306 [00:21<00:58,  4.01it/s]

 24%|██▍       | 73/306 [00:21<00:58,  4.00it/s]

 24%|██▍       | 74/306 [00:21<00:57,  4.01it/s]

 25%|██▍       | 75/306 [00:21<00:57,  4.03it/s]

 25%|██▍       | 76/306 [00:22<00:56,  4.04it/s]

 25%|██▌       | 77/306 [00:22<00:56,  4.05it/s]

 25%|██▌       | 78/306 [00:22<00:56,  4.05it/s]

 26%|██▌       | 79/306 [00:22<00:56,  4.00it/s]

 26%|██▌       | 80/306 [00:23<00:56,  4.00it/s]

 26%|██▋       | 81/306 [00:23<00:55,  4.02it/s]

 27%|██▋       | 82/306 [00:23<00:55,  4.03it/s]

 27%|██▋       | 83/306 [00:23<00:55,  4.02it/s]

 27%|██▋       | 84/306 [00:24<00:55,  3.98it/s]

 28%|██▊       | 85/306 [00:24<00:55,  3.96it/s]

 28%|██▊       | 86/306 [00:24<00:55,  3.97it/s]

 28%|██▊       | 87/306 [00:24<00:55,  3.94it/s]

 29%|██▉       | 88/306 [00:25<00:54,  3.97it/s]

 29%|██▉       | 89/306 [00:25<00:54,  4.00it/s]

 29%|██▉       | 90/306 [00:25<00:53,  4.02it/s]

 30%|██▉       | 91/306 [00:25<00:53,  4.04it/s]

 30%|███       | 92/306 [00:26<00:52,  4.05it/s]

 30%|███       | 93/306 [00:26<00:52,  4.07it/s]

 31%|███       | 94/306 [00:26<00:52,  4.06it/s]

 31%|███       | 95/306 [00:26<00:52,  4.04it/s]

 31%|███▏      | 96/306 [00:27<00:51,  4.04it/s]

 32%|███▏      | 97/306 [00:27<00:51,  4.03it/s]

 32%|███▏      | 98/306 [00:27<00:51,  4.00it/s]

 32%|███▏      | 99/306 [00:27<00:51,  4.01it/s]

 33%|███▎      | 100/306 [00:28<00:51,  4.04it/s]

 33%|███▎      | 101/306 [00:28<00:50,  4.05it/s]

 33%|███▎      | 102/306 [00:28<00:50,  4.05it/s]

 34%|███▎      | 103/306 [00:28<00:50,  4.02it/s]

 34%|███▍      | 104/306 [00:29<00:50,  4.03it/s]

 34%|███▍      | 105/306 [00:29<00:49,  4.04it/s]

 35%|███▍      | 106/306 [00:29<00:49,  4.01it/s]

 35%|███▍      | 107/306 [00:29<00:50,  3.98it/s]

 35%|███▌      | 108/306 [00:30<00:50,  3.95it/s]

 36%|███▌      | 109/306 [00:30<00:49,  3.98it/s]

 36%|███▌      | 110/306 [00:30<00:49,  3.97it/s]

 36%|███▋      | 111/306 [00:30<00:49,  3.94it/s]

 37%|███▋      | 112/306 [00:31<00:48,  3.96it/s]

 37%|███▋      | 113/306 [00:31<00:48,  4.00it/s]

 37%|███▋      | 114/306 [00:31<00:47,  4.03it/s]

 38%|███▊      | 115/306 [00:31<00:47,  4.04it/s]

 38%|███▊      | 116/306 [00:32<00:46,  4.06it/s]

 38%|███▊      | 117/306 [00:32<00:46,  4.08it/s]

 39%|███▊      | 118/306 [00:32<00:45,  4.09it/s]

 39%|███▉      | 119/306 [00:32<00:46,  4.03it/s]

 39%|███▉      | 120/306 [00:33<00:46,  4.02it/s]

 40%|███▉      | 121/306 [00:33<00:45,  4.03it/s]

 40%|███▉      | 122/306 [00:33<00:45,  4.06it/s]

 40%|████      | 123/306 [00:33<00:45,  4.07it/s]

 41%|████      | 124/306 [00:34<00:44,  4.08it/s]

 41%|████      | 125/306 [00:34<00:44,  4.09it/s]

 41%|████      | 126/306 [00:34<00:43,  4.10it/s]

 42%|████▏     | 127/306 [00:34<00:44,  3.98it/s]

 42%|████▏     | 128/306 [00:35<00:44,  4.00it/s]

 42%|████▏     | 129/306 [00:35<00:44,  4.02it/s]

 42%|████▏     | 130/306 [00:35<00:44,  3.96it/s]

 43%|████▎     | 131/306 [00:35<00:44,  3.93it/s]

 43%|████▎     | 132/306 [00:36<00:44,  3.95it/s]

 43%|████▎     | 133/306 [00:36<00:43,  4.00it/s]

 44%|████▍     | 134/306 [00:36<00:43,  3.97it/s]

 44%|████▍     | 135/306 [00:36<00:44,  3.81it/s]

 44%|████▍     | 136/306 [00:37<00:43,  3.87it/s]

 45%|████▍     | 137/306 [00:37<00:43,  3.91it/s]

 45%|████▌     | 138/306 [00:37<00:42,  3.95it/s]

 45%|████▌     | 139/306 [00:37<00:42,  3.97it/s]

 46%|████▌     | 140/306 [00:38<00:41,  3.99it/s]

 46%|████▌     | 141/306 [00:38<00:41,  4.01it/s]

 46%|████▋     | 142/306 [00:38<00:41,  3.93it/s]

 47%|████▋     | 143/306 [00:38<00:41,  3.95it/s]

 47%|████▋     | 144/306 [00:39<00:40,  3.97it/s]

 47%|████▋     | 145/306 [00:39<00:40,  3.97it/s]

 48%|████▊     | 146/306 [00:39<00:40,  3.98it/s]

 48%|████▊     | 147/306 [00:39<00:40,  3.97it/s]

 48%|████▊     | 148/306 [00:40<00:39,  3.98it/s]

 49%|████▊     | 149/306 [00:40<00:39,  4.00it/s]

 49%|████▉     | 150/306 [00:40<00:40,  3.81it/s]

 49%|████▉     | 151/306 [00:40<00:40,  3.83it/s]

 50%|████▉     | 152/306 [00:41<00:39,  3.85it/s]

 50%|█████     | 153/306 [00:41<00:39,  3.88it/s]

 50%|█████     | 154/306 [00:41<00:39,  3.88it/s]

 51%|█████     | 155/306 [00:41<00:38,  3.92it/s]

 51%|█████     | 156/306 [00:42<00:37,  3.96it/s]

 51%|█████▏    | 157/306 [00:42<00:37,  3.99it/s]

 52%|█████▏    | 158/306 [00:42<00:37,  3.91it/s]

 52%|█████▏    | 159/306 [00:43<00:37,  3.91it/s]

 52%|█████▏    | 160/306 [00:43<00:37,  3.93it/s]

 53%|█████▎    | 161/306 [00:43<00:36,  3.96it/s]

 53%|█████▎    | 162/306 [00:43<00:36,  3.98it/s]

 53%|█████▎    | 163/306 [00:44<00:35,  4.01it/s]

 54%|█████▎    | 164/306 [00:44<00:35,  4.02it/s]

 54%|█████▍    | 165/306 [00:44<00:34,  4.04it/s]

 54%|█████▍    | 166/306 [00:44<00:35,  3.95it/s]

 55%|█████▍    | 167/306 [00:45<00:35,  3.95it/s]

 55%|█████▍    | 168/306 [00:45<00:34,  3.96it/s]

 55%|█████▌    | 169/306 [00:45<00:34,  3.95it/s]

 56%|█████▌    | 170/306 [00:45<00:34,  3.93it/s]

 56%|█████▌    | 171/306 [00:46<00:34,  3.96it/s]

 56%|█████▌    | 172/306 [00:46<00:33,  3.99it/s]

 57%|█████▋    | 173/306 [00:46<00:33,  4.00it/s]

 57%|█████▋    | 174/306 [00:46<00:33,  3.97it/s]

 57%|█████▋    | 175/306 [00:47<00:33,  3.92it/s]

 58%|█████▊    | 176/306 [00:47<00:33,  3.92it/s]

 58%|█████▊    | 177/306 [00:47<00:32,  3.93it/s]

 58%|█████▊    | 178/306 [00:47<00:32,  3.95it/s]

 58%|█████▊    | 179/306 [00:48<00:31,  3.97it/s]

 59%|█████▉    | 180/306 [00:48<00:31,  3.98it/s]

 59%|█████▉    | 181/306 [00:48<00:31,  3.94it/s]

 59%|█████▉    | 182/306 [00:48<00:31,  3.95it/s]

 60%|█████▉    | 183/306 [00:49<00:31,  3.95it/s]

 60%|██████    | 184/306 [00:49<00:30,  3.96it/s]

 60%|██████    | 185/306 [00:49<00:30,  3.97it/s]

 61%|██████    | 186/306 [00:49<00:30,  3.99it/s]

 61%|██████    | 187/306 [00:50<00:29,  4.01it/s]

 61%|██████▏   | 188/306 [00:50<00:29,  4.02it/s]

 62%|██████▏   | 189/306 [00:50<00:29,  3.99it/s]

 62%|██████▏   | 190/306 [00:50<00:29,  3.98it/s]

 62%|██████▏   | 191/306 [00:51<00:28,  3.97it/s]

 63%|██████▎   | 192/306 [00:51<00:28,  3.97it/s]

 63%|██████▎   | 193/306 [00:51<00:28,  3.93it/s]

 63%|██████▎   | 194/306 [00:51<00:28,  3.93it/s]

 64%|██████▎   | 195/306 [00:52<00:28,  3.94it/s]

 64%|██████▍   | 196/306 [00:52<00:27,  3.95it/s]

 64%|██████▍   | 197/306 [00:52<00:28,  3.85it/s]

 65%|██████▍   | 198/306 [00:52<00:27,  3.86it/s]

 65%|██████▌   | 199/306 [00:53<00:27,  3.86it/s]

 65%|██████▌   | 200/306 [00:53<00:27,  3.90it/s]

 66%|██████▌   | 201/306 [00:53<00:26,  3.93it/s]

 66%|██████▌   | 202/306 [00:53<00:26,  3.95it/s]

 66%|██████▋   | 203/306 [00:54<00:25,  3.97it/s]

 67%|██████▋   | 204/306 [00:54<00:25,  3.99it/s]

 67%|██████▋   | 205/306 [00:54<00:25,  3.92it/s]

 67%|██████▋   | 206/306 [00:54<00:25,  3.93it/s]

 68%|██████▊   | 207/306 [00:55<00:25,  3.94it/s]

 68%|██████▊   | 208/306 [00:55<00:24,  3.93it/s]

 68%|██████▊   | 209/306 [00:55<00:24,  3.93it/s]

 69%|██████▊   | 210/306 [00:55<00:24,  3.95it/s]

 69%|██████▉   | 211/306 [00:56<00:23,  3.96it/s]

 69%|██████▉   | 212/306 [00:56<00:23,  3.98it/s]

 70%|██████▉   | 213/306 [00:56<00:23,  3.88it/s]

 70%|██████▉   | 214/306 [00:56<00:23,  3.89it/s]

 70%|███████   | 215/306 [00:57<00:23,  3.90it/s]

 71%|███████   | 216/306 [00:57<00:22,  3.92it/s]

 71%|███████   | 217/306 [00:57<00:22,  3.94it/s]

 71%|███████   | 218/306 [00:57<00:22,  3.95it/s]

 72%|███████▏  | 219/306 [00:58<00:21,  3.97it/s]

 72%|███████▏  | 220/306 [00:58<00:21,  3.96it/s]

 72%|███████▏  | 221/306 [00:58<00:22,  3.83it/s]

 73%|███████▎  | 222/306 [00:58<00:21,  3.87it/s]

 73%|███████▎  | 223/306 [00:59<00:21,  3.90it/s]

 73%|███████▎  | 224/306 [00:59<00:20,  3.93it/s]

 74%|███████▎  | 225/306 [00:59<00:20,  3.95it/s]

 74%|███████▍  | 226/306 [00:59<00:20,  3.95it/s]

 74%|███████▍  | 227/306 [01:00<00:19,  3.96it/s]

 75%|███████▍  | 228/306 [01:00<00:19,  3.95it/s]

 75%|███████▍  | 229/306 [01:00<00:19,  3.91it/s]

 75%|███████▌  | 230/306 [01:01<00:19,  3.93it/s]

 75%|███████▌  | 231/306 [01:01<00:19,  3.95it/s]

 76%|███████▌  | 232/306 [01:01<00:18,  3.95it/s]

 76%|███████▌  | 233/306 [01:01<00:18,  3.96it/s]

 76%|███████▋  | 234/306 [01:02<00:18,  3.96it/s]

 77%|███████▋  | 235/306 [01:02<00:17,  3.97it/s]

 77%|███████▋  | 236/306 [01:02<00:17,  3.94it/s]

 77%|███████▋  | 237/306 [01:02<00:17,  3.88it/s]

 78%|███████▊  | 238/306 [01:03<00:17,  3.87it/s]

 78%|███████▊  | 239/306 [01:03<00:17,  3.85it/s]

 78%|███████▊  | 240/306 [01:03<00:17,  3.84it/s]

 79%|███████▉  | 241/306 [01:03<00:16,  3.85it/s]

 79%|███████▉  | 242/306 [01:04<00:16,  3.81it/s]

 79%|███████▉  | 243/306 [01:04<00:16,  3.77it/s]

 80%|███████▉  | 244/306 [01:04<00:16,  3.73it/s]

 80%|████████  | 245/306 [01:04<00:16,  3.77it/s]

 80%|████████  | 246/306 [01:05<00:15,  3.79it/s]

 81%|████████  | 247/306 [01:05<00:15,  3.82it/s]

 81%|████████  | 248/306 [01:05<00:15,  3.82it/s]

 81%|████████▏ | 249/306 [01:05<00:14,  3.84it/s]

 82%|████████▏ | 250/306 [01:06<00:14,  3.88it/s]

 82%|████████▏ | 251/306 [01:06<00:14,  3.89it/s]

 82%|████████▏ | 252/306 [01:06<00:14,  3.86it/s]

 83%|████████▎ | 253/306 [01:06<00:13,  3.88it/s]

 83%|████████▎ | 254/306 [01:07<00:13,  3.91it/s]

 83%|████████▎ | 255/306 [01:07<00:12,  3.93it/s]

 84%|████████▎ | 256/306 [01:07<00:12,  3.95it/s]

 84%|████████▍ | 257/306 [01:07<00:12,  3.96it/s]

 84%|████████▍ | 258/306 [01:08<00:12,  3.95it/s]

 85%|████████▍ | 259/306 [01:08<00:11,  3.96it/s]

 85%|████████▍ | 260/306 [01:08<00:11,  3.92it/s]

 85%|████████▌ | 261/306 [01:08<00:11,  3.93it/s]

 86%|████████▌ | 262/306 [01:09<00:11,  3.94it/s]

 86%|████████▌ | 263/306 [01:09<00:10,  3.93it/s]

 86%|████████▋ | 264/306 [01:09<00:10,  3.92it/s]

 87%|████████▋ | 265/306 [01:10<00:10,  3.87it/s]

 87%|████████▋ | 266/306 [01:10<00:10,  3.90it/s]

 87%|████████▋ | 267/306 [01:10<00:09,  3.93it/s]

 88%|████████▊ | 268/306 [01:10<00:09,  3.90it/s]

 88%|████████▊ | 269/306 [01:11<00:09,  3.92it/s]

 88%|████████▊ | 270/306 [01:11<00:09,  3.92it/s]

 89%|████████▊ | 271/306 [01:11<00:08,  3.94it/s]

 89%|████████▉ | 272/306 [01:11<00:08,  3.96it/s]

 89%|████████▉ | 273/306 [01:12<00:08,  3.98it/s]

 90%|████████▉ | 274/306 [01:12<00:08,  3.99it/s]

 90%|████████▉ | 275/306 [01:12<00:07,  3.98it/s]

 90%|█████████ | 276/306 [01:12<00:07,  3.94it/s]

 91%|█████████ | 277/306 [01:13<00:07,  3.95it/s]

 91%|█████████ | 278/306 [01:13<00:07,  3.97it/s]

 91%|█████████ | 279/306 [01:13<00:06,  3.98it/s]

 92%|█████████▏| 280/306 [01:13<00:06,  3.98it/s]

 92%|█████████▏| 281/306 [01:14<00:06,  3.96it/s]

 92%|█████████▏| 282/306 [01:14<00:06,  3.94it/s]

 92%|█████████▏| 283/306 [01:14<00:05,  3.94it/s]

 93%|█████████▎| 284/306 [01:14<00:05,  3.90it/s]

 93%|█████████▎| 285/306 [01:15<00:05,  3.90it/s]

 93%|█████████▎| 286/306 [01:15<00:05,  3.85it/s]

 94%|█████████▍| 287/306 [01:15<00:04,  3.82it/s]

 94%|█████████▍| 288/306 [01:15<00:04,  3.82it/s]

 94%|█████████▍| 289/306 [01:16<00:04,  3.83it/s]

 95%|█████████▍| 290/306 [01:16<00:04,  3.84it/s]

 95%|█████████▌| 291/306 [01:16<00:04,  3.72it/s]

 95%|█████████▌| 292/306 [01:16<00:03,  3.78it/s]

 96%|█████████▌| 293/306 [01:17<00:03,  3.84it/s]

 96%|█████████▌| 294/306 [01:17<00:03,  3.89it/s]

 96%|█████████▋| 295/306 [01:17<00:02,  3.92it/s]

 97%|█████████▋| 296/306 [01:17<00:02,  3.91it/s]

 97%|█████████▋| 297/306 [01:18<00:02,  3.94it/s]

 97%|█████████▋| 298/306 [01:18<00:02,  3.93it/s]

 98%|█████████▊| 299/306 [01:18<00:01,  3.95it/s]

 98%|█████████▊| 300/306 [01:18<00:01,  3.95it/s]

 98%|█████████▊| 301/306 [01:19<00:01,  3.97it/s]

 99%|█████████▊| 302/306 [01:19<00:01,  3.97it/s]

 99%|█████████▉| 303/306 [01:19<00:00,  3.98it/s]

 99%|█████████▉| 304/306 [01:19<00:00,  3.98it/s]

100%|█████████▉| 305/306 [01:20<00:00,  3.97it/s]

100%|██████████| 306/306 [01:20<00:00,  3.94it/s]

100%|██████████| 306/306 [01:20<00:00,  3.80it/s]

convnext Epoch 3 loss 1.2752 val_acc 0.7880

Saved best convnext to /kaggle/working/writer_convnext_best.pth
Best convnext val_acc: 0.7880

Inference

In [11]:
test_ds = CircleDataset(test_df, DATASET_DIR, val_tfms, is_test=True)

test_loader = DataLoader(
    test_ds,
    batch_size=128,
    num_workers=NUM_WORKERS,
    pin_memory=PIN_MEMORY
)

preds = []

for model in models:

    model.eval()

    fold_preds = []

    with torch.no_grad():

        if IS_XLA:
            inference_loader = pl.MpDeviceLoader(test_loader, device)
        else:
            inference_loader = test_loader

        for images, _ in inference_loader:

            images = images.to(device)

            probs = []

            logits = model(images)
            probs.append(torch.softmax(logits, 1))

            logits = model(torch.flip(images, dims=[3]))
            probs.append(torch.softmax(logits, 1))

            logits = model(torch.flip(images, dims=[2]))
            probs.append(torch.softmax(logits, 1))

            logits = model(torch.rot90(images, 1, [2, 3]))
            probs.append(torch.softmax(logits, 1))

            prob = torch.mean(torch.stack(probs), dim=0)

            fold_preds.append(prob.cpu().numpy())

            if IS_XLA:
                xm.mark_step()

    preds.append(np.concatenate(fold_preds))

preds = np.mean(preds, axis=0)
labels = preds.argmax(1)
confidences = preds.max(axis=1)
CONF_THRESHOLD = 0.35

writer_preds = [
    label_to_writer[int(label)] if confidence >= CONF_THRESHOLD else "-1"
    for label, confidence in zip(labels, confidences)
]

/tmp/ipykernel_74/3589544338.py:48: DeprecationWarning: Use torch_xla.sync instead
  xm.mark_step()

Submission

In [12]:
submission = sample_submission.copy()
submission["writer_id"] = writer_preds
submission.to_csv("submission.csv", index=False)

submission.head()

                              image_id writer_id
0  v2_000010c19b698fe39922ef49ff26ce16       W39
1  v2_000f8ac7d2e0ecf1d336c60fe7f34789        -1
2  v2_001a7e63cc91c92d259c2bc43572824f        -1
3  v2_001dd98a324ee7d88952f2e1d0c29674       W48
4  v2_002e3bc1d82ac5121dccf470ceed4422        -1